-- =====================================================================
-- V7 : Seed du lieu KHOA HOC / BAI HOC / NGU PHAP / TU VUNG BAI HOC
-- Noi dung: courses (id 1..6), lessons (id 1..44),
--           lesson_grammar (bai 1..24), lesson_words (bai 1..24)
-- Quy uoc: id co dinh de cac file seed khac tham chieu duoc,
--          timestamp co dinh '2026-01-01 00:00:00.000000',
--          BIT(1) ghi b'1' / b'0', chuoi UTF-8 (Han tu + pinyin co dau).
-- Phu thuoc: words id 1..150 (HSK1) va 151..300 (HSK2) do file seed
--            tu vung tao ra truoc do.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. COURSES (id 1..6)
-- ---------------------------------------------------------------------
INSERT INTO courses (id, slug, title, description, level, thumbnail_url, published, sort_order, estimated_minutes, created_at, updated_at) VALUES
(1, 'hsk-1-co-ban', 'Tiếng Trung cơ bản HSK 1',
 'Khóa học nhập môn dành cho người mới bắt đầu, không cần biết trước một chữ Hán nào. Bạn sẽ học bảng phiên âm pinyin, bốn thanh điệu, 150 từ vựng HSK 1 và các mẫu câu giao tiếp thiết yếu: chào hỏi, giới thiệu bản thân, gia đình, số đếm, thời gian, mua sắm, đồ ăn và thời tiết. Sau 12 bài học bạn có thể tự tin làm bài thi HSK 1 và giao tiếp trong những tình huống đơn giản hằng ngày.',
 'HSK1', 'https://cdn.hoctiengtrung.vn/courses/hsk1-co-ban.jpg', b'1', 1, 720, '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(2, 'hsk-2-so-cap', 'Tiếng Trung sơ cấp HSK 2',
 'Tiếp nối HSK 1, khóa học mở rộng vốn từ lên 300 từ và bổ sung các cấu trúc ngữ pháp quan trọng như so sánh với 比, bổ ngữ trạng thái với 得, trợ từ 了 và 过. Nội dung xoay quanh những tình huống thực tế: hỏi đường, gọi món trong nhà hàng, đi khám bệnh, đặt phòng khách sạn, gọi điện hẹn gặp và miêu tả người. Kết thúc khóa học bạn đủ khả năng vượt qua kỳ thi HSK 2 và duy trì hội thoại ngắn bằng tiếng Trung.',
 'HSK2', 'https://cdn.hoctiengtrung.vn/courses/hsk2-so-cap.jpg', b'1', 2, 840, '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(3, 'hsk-3-trung-cap', 'Tiếng Trung trung cấp HSK 3',
 'Khóa học đưa bạn từ trình độ giao tiếp cơ bản lên mức có thể kể chuyện, trình bày ý kiến và xử lý hầu hết tình huống khi sinh sống, học tập tại Trung Quốc. Trọng tâm là 600 từ vựng HSK 3, hệ thống bổ ngữ kết quả và bổ ngữ xu hướng, câu chữ 把, câu bị động và các liên từ phức hợp. Mỗi bài đều có phần luyện nghe, luyện đọc và bài tập viết chữ Hán.',
 'HSK3', 'https://cdn.hoctiengtrung.vn/courses/hsk3-trung-cap.jpg', b'1', 3, 960, '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(4, 'hsk-4-nang-cao', 'Tiếng Trung nâng cao HSK 4',
 'Lộ trình nâng cao với 1200 từ vựng HSK 4, giúp bạn thảo luận về công việc, xã hội, môi trường và bày tỏ quan điểm cá nhân một cách mạch lạc. Khóa học tập trung vào cụm từ cố định, cách dùng thành ngữ thông dụng, kỹ năng đọc hiểu văn bản dài và viết đoạn văn 80 chữ theo yêu cầu đề thi. Nội dung đang được biên soạn và sẽ mở trong thời gian tới.',
 'HSK4', 'https://cdn.hoctiengtrung.vn/courses/hsk4-nang-cao.jpg', b'0', 4, 1080, '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(5, 'hsk-5-cao-cap', 'Tiếng Trung cao cấp HSK 5',
 'Khóa học dành cho người học đã vững HSK 4, hướng tới 2500 từ vựng và khả năng đọc báo, xem phim, nghe tin tức tiếng Trung mà không cần phụ đề. Chương trình đi sâu vào thành ngữ bốn chữ, văn phong viết, tiếng Trung thương mại và kỹ năng thuyết trình, tranh luận. Đây là bản đề cương, các bài học chi tiết sẽ được cập nhật sau.',
 'HSK5', 'https://cdn.hoctiengtrung.vn/courses/hsk5-cao-cap.jpg', b'0', 5, 1200, '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(6, 'hsk-6-thanh-thao', 'Tiếng Trung thành thạo HSK 6',
 'Cấp độ cao nhất của hệ thống HSK với hơn 5000 từ vựng, hướng tới năng lực sử dụng tiếng Trung gần như người bản ngữ trong môi trường học thuật và chuyên môn. Khóa học rèn văn viết trang trọng, điển cố và Hán ngữ cổ còn dùng trong văn viết hiện đại, phân tích văn bản học thuật và chiến lược luyện thi HSK 6. Đề cương tham khảo, nội dung chi tiết đang xây dựng.',
 'HSK6', 'https://cdn.hoctiengtrung.vn/courses/hsk6-thanh-thao.jpg', b'0', 6, 1440, '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000');

-- ---------------------------------------------------------------------
-- 2. LESSONS - Khoa 1 : HSK 1 co ban (id 1..12)
-- ---------------------------------------------------------------------
INSERT INTO lessons (id, course_id, slug, title, summary, content, video_url, audio_url, sort_order, estimated_minutes, published, created_at, updated_at) VALUES
(1, 1, 'chao-hoi-lam-quen', 'Bài 1: Chào hỏi và làm quen',
 'Học cách chào hỏi, hỏi thăm sức khỏe, giới thiệu tên và quốc tịch. Nắm quy tắc biến điệu khi hai thanh 3 đứng liền nhau trong 你好.',
 '## Mục tiêu bài học\nSau bài này bạn có thể chào hỏi, giới thiệu tên và hỏi thăm người đối diện hoàn toàn bằng tiếng Trung.\n\n## Mẫu câu trọng tâm\n1. 你好！(Nǐ hǎo!) — Xin chào!\n2. 你好吗？(Nǐ hǎo ma?) — Bạn khỏe không?\n3. 我很好，谢谢。(Wǒ hěn hǎo, xièxie.) — Tôi khỏe, cảm ơn.\n4. 你叫什么名字？(Nǐ jiào shénme míngzi?) — Bạn tên là gì?\n5. 我叫阮明。(Wǒ jiào Ruǎn Míng.) — Tôi tên là Nguyễn Minh.\n6. 我是越南人。(Wǒ shì Yuènán rén.) — Tôi là người Việt Nam.\n7. 认识你很高兴。(Rènshi nǐ hěn gāoxìng.) — Rất vui được làm quen với bạn.\n\n## Ghi chú phát âm\nTừ 你好 có hai thanh 3 đứng liền nhau. Khi đọc, thanh 3 thứ nhất biến thành thanh 2, nghe thành ní hǎo. Quy tắc này áp dụng cho mọi cặp thanh 3 liên tiếp, ví dụ 很好 đọc thành hén hǎo.\n\n## Luyện tập\nĐọc to đoạn tự giới thiệu sau rồi thay bằng thông tin của bạn: 你好！我叫阮明，我是越南人。认识你很高兴。',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-01.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-01.mp3', 1, 45, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(2, 1, 'so-dem-ngay-thang', 'Bài 2: Số đếm, ngày tháng và tuổi tác',
 'Đếm từ 0 đến 100, hỏi hôm nay ngày mấy, thứ mấy và hỏi tuổi. Phân biệt cách dùng 几 với 多少.',
 '## Mục tiêu bài học\nĐếm số thành thạo, nói được ngày tháng, thứ trong tuần và hỏi tuổi người khác.\n\n## Số đếm cơ bản\n零 líng 0, 一 yī 1, 二 èr 2, 三 sān 3, 四 sì 4, 五 wǔ 5, 六 liù 6, 七 qī 7, 八 bā 8, 九 jiǔ 9, 十 shí 10.\nTừ 11 đến 99 ghép rất đều đặn: 十一 (11), 二十 (20), 二十五 (25), 九十九 (99), 一百 (100).\n\n## Mẫu câu trọng tâm\n1. 今天几号？(Jīntiān jǐ hào?) — Hôm nay ngày mấy?\n2. 今天十月一号。(Jīntiān shíyuè yī hào.) — Hôm nay ngày 1 tháng 10.\n3. 明天星期几？(Míngtiān xīngqī jǐ?) — Ngày mai thứ mấy?\n4. 明天星期三。(Míngtiān xīngqīsān.) — Ngày mai thứ Tư.\n5. 你今年多大？(Nǐ jīnnián duō dà?) — Năm nay bạn bao nhiêu tuổi?\n6. 我今年二十岁。(Wǒ jīnnián èrshí suì.) — Năm nay tôi 20 tuổi.\n\n## Lưu ý quan trọng\nTrật tự thời gian trong tiếng Trung luôn đi từ đơn vị lớn đến đơn vị nhỏ: 年 đứng trước 月, rồi mới tới 号. Ví dụ 2026年1月1号.\n\n## Luyện tập\nViết ngày sinh của bạn bằng tiếng Trung theo đúng trật tự trên rồi đọc to ba lần.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-02.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-02.mp3', 2, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(3, 1, 'gia-dinh-cua-toi', 'Bài 3: Gia đình của tôi',
 'Gọi tên các thành viên trong gia đình, nói nhà có mấy người và giới thiệu nghề nghiệp của bố mẹ.',
 '## Mục tiêu bài học\nGiới thiệu được các thành viên trong gia đình và số người trong nhà.\n\n## Từ vựng trọng tâm\n爸爸 bàba (bố), 妈妈 māma (mẹ), 哥哥 gēge (anh trai), 姐姐 jiějie (chị gái), 弟弟 dìdi (em trai), 妹妹 mèimei (em gái), 儿子 érzi (con trai), 女儿 nǚ''ér (con gái).\n\n## Mẫu câu trọng tâm\n1. 你家有几口人？(Nǐ jiā yǒu jǐ kǒu rén?) — Nhà bạn có mấy người?\n2. 我家有四口人。(Wǒ jiā yǒu sì kǒu rén.) — Nhà tôi có bốn người.\n3. 爸爸、妈妈、姐姐和我。(Bàba, māma, jiějie hé wǒ.) — Bố, mẹ, chị gái và tôi.\n4. 这是我的妈妈。(Zhè shì wǒ de māma.) — Đây là mẹ của tôi.\n5. 我爸爸是医生。(Wǒ bàba shì yīshēng.) — Bố tôi là bác sĩ.\n\n## Ghi chú ngữ pháp\nLượng từ đếm nhân khẩu trong gia đình là 口 chứ không phải 个: nói 五口人, không nói 五个人. Với quan hệ thân thiết như 我妈妈 hay 我家, chữ 的 thường được lược bỏ.\n\n## Luyện tập\nVẽ sơ đồ gia đình bạn rồi viết một câu giới thiệu bằng tiếng Trung cho từng người.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-03.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-03.mp3', 3, 45, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(4, 1, 'thoi-gian-gio-giac', 'Bài 4: Thời gian và giờ giấc',
 'Xem giờ bằng tiếng Trung, kể lịch sinh hoạt một ngày và đặt trạng ngữ thời gian đúng vị trí trong câu.',
 '## Mục tiêu bài học\nHỏi và trả lời mấy giờ, mô tả được thời gian biểu một ngày của bạn.\n\n## Mẫu câu trọng tâm\n1. 现在几点？(Xiànzài jǐ diǎn?) — Bây giờ mấy giờ?\n2. 现在八点。(Xiànzài bā diǎn.) — Bây giờ 8 giờ.\n3. 现在八点半。(Xiànzài bā diǎn bàn.) — Bây giờ 8 giờ rưỡi.\n4. 我七点起床。(Wǒ qī diǎn qǐchuáng.) — Tôi thức dậy lúc 7 giờ.\n5. 我们十二点吃午饭。(Wǒmen shí''èr diǎn chī wǔfàn.) — Chúng tôi ăn trưa lúc 12 giờ.\n6. 你什么时候去学校？(Nǐ shénme shíhou qù xuéxiào?) — Khi nào bạn đi học?\n\n## Ghi chú ngữ pháp\nĐiểm khác biệt lớn nhất so với tiếng Việt: trạng ngữ thời gian luôn đứng TRƯỚC động từ. Tiếng Việt nói tôi đi học lúc 7 giờ, tiếng Trung bắt buộc nói 我七点去学校. Có thể đưa thời gian lên đầu câu để nhấn mạnh: 七点我去学校。\n\n## Luyện tập\nViết năm câu về thời gian biểu của bạn, mỗi câu mở đầu bằng một mốc giờ khác nhau.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-04.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-04.mp3', 4, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(5, 1, 'do-an-thuc-uong', 'Bài 5: Đồ ăn và thức uống',
 'Nói về món ăn yêu thích, gọi đồ uống và dùng động từ năng nguyện 想 để bày tỏ mong muốn.',
 '## Mục tiêu bài học\nNói được bạn thích ăn gì, muốn uống gì và từ chối lịch sự khi không thích món nào đó.\n\n## Từ vựng trọng tâm\n米饭 mǐfàn (cơm), 面条 miàntiáo (mì), 菜 cài (món ăn), 肉 ròu (thịt), 鱼 yú (cá), 水果 shuǐguǒ (hoa quả), 苹果 píngguǒ (táo), 水 shuǐ (nước), 茶 chá (trà), 咖啡 kāfēi (cà phê).\n\n## Mẫu câu trọng tâm\n1. 我很喜欢吃中国菜。(Wǒ hěn xǐhuan chī Zhōngguó cài.) — Tôi rất thích ăn món Trung Quốc.\n2. 我想喝一杯茶。(Wǒ xiǎng hē yì bēi chá.) — Tôi muốn uống một tách trà.\n3. 你想吃什么？(Nǐ xiǎng chī shénme?) — Bạn muốn ăn gì?\n4. 我不吃肉。(Wǒ bù chī ròu.) — Tôi không ăn thịt.\n5. 这个菜很好吃。(Zhège cài hěn hǎochī.) — Món này rất ngon.\n\n## Ghi chú ngữ pháp\n想 đứng trước động từ để diễn tả mong muốn, dạng phủ định là 不想. Tính từ 好 ghép với động từ tạo ra từ mới: 好吃 (ngon), 好喝 (uống ngon), 好看 (đẹp mắt).\n\n## Luyện tập\nĐóng vai gọi món: một người hỏi 你想吃什么, người kia trả lời bằng ba món khác nhau.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-05.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-05.mp3', 5, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(6, 1, 'mua-sam-gia-ca', 'Bài 6: Mua sắm và hỏi giá',
 'Hỏi giá tiền, đếm tiền Nhân dân tệ, dùng lượng từ 个 và 本 khi mua đồ, biết nói mặc cả cơ bản.',
 '## Mục tiêu bài học\nTự tin đi chợ và siêu thị: hỏi giá, mặc cả và nói số lượng muốn mua.\n\n## Mẫu câu trọng tâm\n1. 这个多少钱？(Zhège duōshao qián?) — Cái này bao nhiêu tiền?\n2. 十五块钱。(Shíwǔ kuài qián.) — Mười lăm tệ.\n3. 太贵了！(Tài guì le!) — Đắt quá!\n4. 便宜一点儿吧。(Piányi yìdiǎnr ba.) — Bớt một chút đi.\n5. 我买两个苹果。(Wǒ mǎi liǎng ge píngguǒ.) — Tôi mua hai quả táo.\n6. 我要这本书。(Wǒ yào zhè běn shū.) — Tôi lấy quyển sách này.\n\n## Ghi chú ngữ pháp\nKhi đếm số lượng phải dùng 两 chứ không dùng 二: nói 两个人, không nói 二个人. Mỗi nhóm danh từ đi với một lượng từ riêng: 个 dùng chung cho người và vật, 本 dùng cho sách vở, 件 dùng cho quần áo.\n\n## Luyện tập\nHỏi giá năm món đồ trong phòng bạn theo mẫu 这个多少钱 rồi tự trả lời bằng tiếng Trung.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-06.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-06.mp3', 6, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(7, 1, 'nha-cua-do-vat', 'Bài 7: Nhà cửa và đồ vật quen thuộc',
 'Gọi tên các phòng và đồ vật trong nhà, dùng động từ 在 cùng các từ chỉ phương vị 上, 里 để nói vị trí.',
 '## Mục tiêu bài học\nMiêu tả ngôi nhà của bạn và nói được đồ vật đang nằm ở đâu.\n\n## Từ vựng trọng tâm\n家 jiā (nhà), 桌子 zhuōzi (cái bàn), 椅子 yǐzi (cái ghế), 电视 diànshì (tivi), 电脑 diànnǎo (máy tính), 手机 shǒujī (điện thoại), 书 shū (sách), 杯子 bēizi (cái cốc).\n\n## Mẫu câu trọng tâm\n1. 书在桌子上。(Shū zài zhuōzi shàng.) — Sách ở trên bàn.\n2. 我的手机在哪儿？(Wǒ de shǒujī zài nǎr?) — Điện thoại của tôi ở đâu?\n3. 手机在椅子上。(Shǒujī zài yǐzi shàng.) — Điện thoại ở trên ghế.\n4. 房间里有一台电脑。(Fángjiān lǐ yǒu yì tái diànnǎo.) — Trong phòng có một cái máy tính.\n5. 这是我的家。(Zhè shì wǒ de jiā.) — Đây là nhà của tôi.\n\n## Ghi chú ngữ pháp\nCấu trúc chỉ vị trí là: Vật + 在 + Nơi chốn. Từ chỉ phương vị 上 (trên), 里 (trong), 下 (dưới) phải đặt SAU danh từ nơi chốn, ngược hoàn toàn với tiếng Việt: 桌子上 nghĩa là trên bàn.\n\n## Luyện tập\nChọn năm đồ vật quanh bạn và viết vị trí của chúng theo mẫu A 在 B 上。',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-07.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-07.mp3', 7, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(8, 1, 'truong-hoc-hoc-tap', 'Bài 8: Trường học và việc học tiếng Trung',
 'Nói về việc học tập, dùng động từ năng nguyện 会 và 能, giới thiệu bạn học tiếng Trung ở đâu.',
 '## Mục tiêu bài học\nNói được bạn học gì, học ở đâu và biết nói mấy thứ tiếng.\n\n## Từ vựng trọng tâm\n学校 xuéxiào (trường học), 老师 lǎoshī (giáo viên), 学生 xuésheng (học sinh), 同学 tóngxué (bạn học), 汉语 Hànyǔ (tiếng Hán), 字 zì (chữ), 书 shū (sách), 学习 xuéxí (học tập).\n\n## Mẫu câu trọng tâm\n1. 我是学生。(Wǒ shì xuésheng.) — Tôi là học sinh.\n2. 我在大学学习汉语。(Wǒ zài dàxué xuéxí Hànyǔ.) — Tôi học tiếng Trung ở trường đại học.\n3. 我会说一点儿汉语。(Wǒ huì shuō yìdiǎnr Hànyǔ.) — Tôi biết nói một chút tiếng Trung.\n4. 老师，请再说一遍。(Lǎoshī, qǐng zài shuō yí biàn.) — Thưa cô, xin nói lại một lần nữa.\n5. 汉语很有意思。(Hànyǔ hěn yǒu yìsi.) — Tiếng Trung rất thú vị.\n\n## Ghi chú ngữ pháp\n会 diễn tả kỹ năng học mà có, ví dụ 我会开车 (tôi biết lái xe). 能 nhấn mạnh điều kiện cho phép hoặc khả năng ở thời điểm cụ thể: 我今天不能去 (hôm nay tôi không đi được).\n\n## Luyện tập\nViết ba câu với 会 nói về những việc bạn biết làm và hai câu với 不会.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-08.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-08.mp3', 8, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(9, 1, 'thoi-tiet-bon-mua', 'Bài 9: Thời tiết và bốn mùa',
 'Miêu tả thời tiết bằng câu vị ngữ tính từ với 很, hỏi thời tiết bằng 怎么样 và nói về bốn mùa trong năm.',
 '## Mục tiêu bài học\nHỏi và miêu tả thời tiết hôm nay, nói bạn thích mùa nào.\n\n## Từ vựng trọng tâm\n天气 tiānqì (thời tiết), 热 rè (nóng), 冷 lěng (lạnh), 下雨 xiàyǔ (mưa), 风 fēng (gió), 春天 chūntiān (mùa xuân), 夏天 xiàtiān (mùa hè), 秋天 qiūtiān (mùa thu), 冬天 dōngtiān (mùa đông).\n\n## Mẫu câu trọng tâm\n1. 今天天气怎么样？(Jīntiān tiānqì zěnmeyàng?) — Thời tiết hôm nay thế nào?\n2. 今天很热。(Jīntiān hěn rè.) — Hôm nay rất nóng.\n3. 今天不冷。(Jīntiān bù lěng.) — Hôm nay không lạnh.\n4. 昨天下雨了。(Zuótiān xiàyǔ le.) — Hôm qua trời đã mưa.\n5. 我喜欢秋天。(Wǒ xǐhuan qiūtiān.) — Tôi thích mùa thu.\n\n## Ghi chú ngữ pháp\nCâu vị ngữ tính từ trong tiếng Trung không cần động từ 是. Nói 今天很热 chứ tuyệt đối không nói 今天是热. Chữ 很 ở đây phần lớn chỉ giữ vai trò liên kết, không nhất thiết mang nghĩa rất.\n\n## Luyện tập\nGhi lại thời tiết bảy ngày trong tuần bằng bảy câu tiếng Trung khác nhau.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-09.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-09.mp3', 9, 45, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(10, 1, 'di-lai-phuong-huong', 'Bài 10: Đi lại và phương tiện giao thông',
 'Nói bạn đi đâu, đi bằng phương tiện gì với cấu trúc 坐 + phương tiện + 去 + địa điểm, hỏi bằng 怎么.',
 '## Mục tiêu bài học\nNói được bạn đi đâu và đi bằng phương tiện nào.\n\n## Từ vựng trọng tâm\n出租车 chūzūchē (taxi), 公共汽车 gōnggòng qìchē (xe buýt), 飞机 fēijī (máy bay), 火车 huǒchē (tàu hỏa), 自行车 zìxíngchē (xe đạp), 走 zǒu (đi bộ), 去 qù (đi tới), 来 lái (đến).\n\n## Mẫu câu trọng tâm\n1. 你去哪儿？(Nǐ qù nǎr?) — Bạn đi đâu đấy?\n2. 我去学校。(Wǒ qù xuéxiào.) — Tôi đi tới trường.\n3. 你怎么去学校？(Nǐ zěnme qù xuéxiào?) — Bạn đi tới trường bằng gì?\n4. 我坐公共汽车去学校。(Wǒ zuò gōnggòng qìchē qù xuéxiào.) — Tôi đi xe buýt tới trường.\n5. 我明天坐飞机去北京。(Wǒ míngtiān zuò fēijī qù Běijīng.) — Ngày mai tôi bay đi Bắc Kinh.\n\n## Ghi chú ngữ pháp\nĐây là câu liên động: hai động từ nối tiếp nhau theo đúng trình tự xảy ra. Phương tiện đứng trước, đích đến đứng sau: 坐出租车去医院. Riêng xe đạp và xe máy dùng động từ 骑 chứ không dùng 坐.\n\n## Luyện tập\nViết bốn câu kể cách bạn đi tới trường, đi làm, về quê và đi du lịch.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-10.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-10.mp3', 10, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(11, 1, 'suc-khoe-co-the', 'Bài 11: Sức khỏe và cơ thể',
 'Nói về tình trạng sức khỏe, dùng 了 chỉ sự thay đổi trạng thái và phân biệt phủ định 不 với 没.',
 '## Mục tiêu bài học\nNói được bạn bị ốm ở đâu, xin nghỉ và chúc người khác mau khỏe.\n\n## Từ vựng trọng tâm\n身体 shēntǐ (cơ thể, sức khỏe), 医生 yīshēng (bác sĩ), 医院 yīyuàn (bệnh viện), 病 bìng (bệnh), 头 tóu (đầu), 眼睛 yǎnjing (mắt), 休息 xiūxi (nghỉ ngơi), 药 yào (thuốc).\n\n## Mẫu câu trọng tâm\n1. 你怎么了？(Nǐ zěnme le?) — Bạn làm sao vậy?\n2. 我生病了。(Wǒ shēngbìng le.) — Tôi bị ốm rồi.\n3. 我头疼。(Wǒ tóu téng.) — Tôi đau đầu.\n4. 你要多休息。(Nǐ yào duō xiūxi.) — Bạn cần nghỉ ngơi nhiều.\n5. 我没去医院。(Wǒ méi qù yīyuàn.) — Tôi đã không đi bệnh viện.\n\n## Ghi chú ngữ pháp\nTrợ từ 了 cuối câu báo hiệu một thay đổi trạng thái: 我生病了 nghĩa là trước đó khỏe, bây giờ đã ốm. Phủ định việc chưa hoặc đã không xảy ra dùng 没 chứ không dùng 不: nói 我没去, không nói 我不去了 nếu muốn kể về quá khứ.\n\n## Luyện tập\nĐóng vai bệnh nhân và bác sĩ, dùng ít nhất bốn mẫu câu ở trên.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-11.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-11.mp3', 11, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(12, 1, 'on-tap-tong-hop-hsk1', 'Bài 12: Ôn tập tổng hợp HSK 1',
 'Hệ thống lại trật tự câu cơ bản, ba kiểu câu hỏi thường gặp và luyện đề thi HSK 1 hoàn chỉnh.',
 '## Mục tiêu bài học\nHệ thống lại toàn bộ kiến thức HSK 1 và làm quen cấu trúc đề thi thật.\n\n## Trật tự câu cơ bản\nChủ ngữ + Thời gian + Địa điểm + Phương thức + Động từ + Tân ngữ.\nVí dụ đầy đủ: 我明天在家跟朋友看电视。(Wǒ míngtiān zài jiā gēn péngyou kàn diànshì.) — Ngày mai tôi xem tivi với bạn ở nhà.\n\n## Ba kiểu câu hỏi cần nhớ\n1. Câu hỏi với 吗: 你是学生吗？(Nǐ shì xuésheng ma?) — Bạn là học sinh phải không?\n2. Câu hỏi chính phản: 你去不去？(Nǐ qù bu qù?) — Bạn có đi không?\n3. Câu hỏi có từ để hỏi: 你叫什么名字？谁？哪儿？几点？多少钱？\n\n## Cấu trúc đề thi HSK 1\nĐề gồm 20 câu nghe và 20 câu đọc, tổng 200 điểm, đạt 120 điểm là qua. Thí sinh có 40 phút làm bài, đề in kèm pinyin nên chưa cần viết chữ Hán.\n\n## Luyện tập\nLàm một đề HSK 1 mẫu trong 40 phút, sau đó ôn lại tất cả những từ bị sai.',
 'https://cdn.hoctiengtrung.vn/videos/hsk1-bai-12.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk1-bai-12.mp3', 12, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000');

-- ---------------------------------------------------------------------
-- 3. LESSONS - Khoa 2 : HSK 2 so cap (id 13..24)
-- ---------------------------------------------------------------------
INSERT INTO lessons (id, course_id, slug, title, summary, content, video_url, audio_url, sort_order, estimated_minutes, published, created_at, updated_at) VALUES
(13, 2, 'hoi-duong-giao-thong', 'Bài 1: Hỏi đường và đi lại trong thành phố',
 'Hỏi đường tới một địa điểm, dùng cấu trúc 从…到… và giới từ 离 để nói khoảng cách xa gần.',
 '## Mục tiêu bài học\nHỏi đường tới ngân hàng, bệnh viện, ga tàu và hiểu được chỉ dẫn của người bản xứ.\n\n## Mẫu câu trọng tâm\n1. 请问，火车站怎么走？(Qǐngwèn, huǒchēzhàn zěnme zǒu?) — Xin hỏi, ga tàu đi thế nào ạ?\n2. 一直往前走。(Yìzhí wǎng qián zǒu.) — Cứ đi thẳng về phía trước.\n3. 到红绿灯往右拐。(Dào hónglǜdēng wǎng yòu guǎi.) — Tới đèn giao thông thì rẽ phải.\n4. 从这儿到医院远吗？(Cóng zhèr dào yīyuàn yuǎn ma?) — Từ đây tới bệnh viện có xa không?\n5. 不远，离这儿很近。(Bù yuǎn, lí zhèr hěn jìn.) — Không xa, cách đây rất gần.\n6. 走路大概要十分钟。(Zǒulù dàgài yào shí fēnzhōng.) — Đi bộ khoảng 10 phút.\n\n## Ghi chú ngữ pháp\n从…到… dùng cho cả không gian lẫn thời gian: 从北京到上海, 从八点到十点. Giới từ 离 chuyên dùng để nói khoảng cách giữa hai điểm và thường đi với 远 hoặc 近.\n\n## Luyện tập\nDùng bản đồ khu bạn ở, viết đoạn hội thoại chỉ đường từ nhà bạn tới chợ gần nhất.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-01.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-01.mp3', 1, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(14, 2, 'goi-mon-nha-hang', 'Bài 2: Gọi món trong nhà hàng',
 'Đặt bàn, gọi món, yêu cầu thêm bớt gia vị và thanh toán. Luyện câu hỏi lựa chọn với 还是.',
 '## Mục tiêu bài học\nGọi được một bữa ăn hoàn chỉnh trong nhà hàng Trung Quốc.\n\n## Mẫu câu trọng tâm\n1. 服务员，点菜。(Fúwùyuán, diǎn cài.) — Anh phục vụ ơi, cho gọi món.\n2. 我要一碗牛肉面。(Wǒ yào yì wǎn niúròu miàn.) — Cho tôi một bát mì bò.\n3. 你喝茶还是喝咖啡？(Nǐ hē chá háishi hē kāfēi?) — Bạn uống trà hay uống cà phê?\n4. 请少放一点儿盐。(Qǐng shǎo fàng yìdiǎnr yán.) — Làm ơn cho ít muối thôi.\n5. 这个菜有点儿辣。(Zhège cài yǒudiǎnr là.) — Món này hơi cay.\n6. 服务员，买单。(Fúwùyuán, mǎidān.) — Anh ơi, tính tiền.\n\n## Ghi chú ngữ pháp\nPhân biệt 有点儿 và 一点儿: 有点儿 đứng TRƯỚC tính từ và mang sắc thái phàn nàn (这个菜有点儿贵), còn 一点儿 đứng SAU tính từ để nói mức độ nhẹ (便宜一点儿). Câu hỏi lựa chọn dùng 还是, không dùng 或者.\n\n## Luyện tập\nViết thực đơn năm món yêu thích của bạn kèm pinyin rồi tập gọi món với bạn học.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-02.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-02.mp3', 2, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(15, 2, 'so-thich-thoi-gian-ranh', 'Bài 3: Sở thích và thời gian rảnh',
 'Nói về sở thích, tần suất làm một việc với 常常, 有时候 và bày tỏ cảm nhận bằng 觉得.',
 '## Mục tiêu bài học\nKể về sở thích của bạn và hỏi sở thích của người khác.\n\n## Từ vựng trọng tâm\n爱好 àihào (sở thích), 运动 yùndòng (thể thao), 踢足球 tī zúqiú (đá bóng), 唱歌 chànggē (hát), 跳舞 tiàowǔ (nhảy múa), 旅游 lǚyóu (du lịch), 看书 kàn shū (đọc sách).\n\n## Mẫu câu trọng tâm\n1. 你有什么爱好？(Nǐ yǒu shénme àihào?) — Bạn có sở thích gì?\n2. 我喜欢运动，特别是游泳。(Wǒ xǐhuan yùndòng, tèbié shì yóuyǒng.) — Tôi thích thể thao, nhất là bơi.\n3. 我常常跟朋友去踢足球。(Wǒ chángcháng gēn péngyou qù tī zúqiú.) — Tôi thường đi đá bóng với bạn.\n4. 有时候我在家看电影。(Yǒu shíhou wǒ zài jiā kàn diànyǐng.) — Thỉnh thoảng tôi xem phim ở nhà.\n5. 我觉得唱歌很有意思。(Wǒ juéde chànggē hěn yǒu yìsi.) — Tôi thấy hát rất thú vị.\n\n## Ghi chú ngữ pháp\nCác phó từ tần suất 常常, 经常, 有时候 đứng trước động từ. 觉得 dùng để nêu cảm nhận chủ quan, theo sau là cả một mệnh đề: 我觉得汉语不太难。\n\n## Luyện tập\nViết đoạn văn năm câu về cách bạn dùng thời gian rảnh cuối tuần.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-03.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-03.mp3', 3, 50, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(16, 2, 'cong-viec-nghe-nghiep', 'Bài 4: Công việc và nghề nghiệp',
 'Giới thiệu nghề nghiệp, nơi làm việc với giới từ 在 và giải thích lý do bằng 因为…所以….',
 '## Mục tiêu bài học\nGiới thiệu công việc của bạn và hỏi về công việc của người khác.\n\n## Từ vựng trọng tâm\n工作 gōngzuò (công việc), 公司 gōngsī (công ty), 老板 lǎobǎn (sếp), 同事 tóngshì (đồng nghiệp), 会议 huìyì (cuộc họp), 忙 máng (bận), 累 lèi (mệt), 上班 shàngbān (đi làm).\n\n## Mẫu câu trọng tâm\n1. 你做什么工作？(Nǐ zuò shénme gōngzuò?) — Bạn làm nghề gì?\n2. 我在一家中国公司工作。(Wǒ zài yì jiā Zhōngguó gōngsī gōngzuò.) — Tôi làm việc ở một công ty Trung Quốc.\n3. 我每天八点上班。(Wǒ měi tiān bā diǎn shàngbān.) — Ngày nào tôi cũng đi làm lúc 8 giờ.\n4. 因为工作很忙，所以我很累。(Yīnwèi gōngzuò hěn máng, suǒyǐ wǒ hěn lèi.) — Vì công việc bận nên tôi rất mệt.\n5. 下午我们有一个会议。(Xiàwǔ wǒmen yǒu yí ge huìyì.) — Chiều nay chúng tôi có một cuộc họp.\n\n## Ghi chú ngữ pháp\nGiới từ 在 chỉ nơi chốn phải đứng TRƯỚC động từ: 我在公司工作, tuyệt đối không nói 我工作在公司. Cặp liên từ 因为…所以… thường dùng đủ cả hai vế, khác tiếng Việt hay lược bớt.\n\n## Luyện tập\nViết đoạn tự giới thiệu bản thân trong buổi phỏng vấn gồm tên, tuổi, nơi làm việc và lý do bạn học tiếng Trung.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-04.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-04.mp3', 4, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(17, 2, 'mua-sam-nang-cao', 'Bài 5: Mua sắm nâng cao, mặc cả và đổi trả',
 'So sánh hai món đồ bằng câu chữ 比, xin phép bằng 可以 và xử lý tình huống đổi trả hàng.',
 '## Mục tiêu bài học\nSo sánh hàng hóa, mặc cả và đổi trả món đồ không vừa ý.\n\n## Mẫu câu trọng tâm\n1. 这件衣服比那件贵。(Zhè jiàn yīfu bǐ nà jiàn guì.) — Chiếc áo này đắt hơn chiếc kia.\n2. 红色的比白色的好看。(Hóngsè de bǐ báisè de hǎokàn.) — Cái màu đỏ đẹp hơn cái màu trắng.\n3. 可以便宜一点儿吗？(Kěyǐ piányi yìdiǎnr ma?) — Có thể bớt chút được không?\n4. 我可以试试吗？(Wǒ kěyǐ shìshi ma?) — Tôi mặc thử được không?\n5. 这个太小了，能换吗？(Zhège tài xiǎo le, néng huàn ma?) — Cái này nhỏ quá, đổi được không?\n\n## Ghi chú ngữ pháp\nCâu chữ 比 có công thức: A + 比 + B + tính từ. Không được thêm 很 hay 太 vào sau tính từ, phải nói 他比我高 chứ không nói 他比我很高. Muốn nói rõ mức chênh lệch thì thêm sau tính từ: 他比我高五厘米。\n\n## Luyện tập\nSo sánh năm cặp đồ vật quanh bạn bằng năm câu dùng 比.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-05.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-05.mp3', 5, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(18, 2, 'di-kham-benh', 'Bài 6: Đi khám bệnh',
 'Mô tả triệu chứng cho bác sĩ, hiểu lời dặn dùng thuốc và luyện câu cầu khiến phủ định với 别.',
 '## Mục tiêu bài học\nMô tả triệu chứng và hiểu lời dặn của bác sĩ ở bệnh viện Trung Quốc.\n\n## Mẫu câu trọng tâm\n1. 我觉得不太舒服。(Wǒ juéde bú tài shūfu.) — Tôi thấy hơi khó chịu trong người.\n2. 我发烧了，还咳嗽。(Wǒ fāshāo le, hái késou.) — Tôi bị sốt, còn bị ho nữa.\n3. 你哪儿不舒服？(Nǐ nǎr bù shūfu?) — Bạn khó chịu ở đâu?\n4. 你要多喝热水，多休息。(Nǐ yào duō hē rè shuǐ, duō xiūxi.) — Bạn cần uống nhiều nước ấm và nghỉ ngơi nhiều.\n5. 别吃太冷的东西。(Bié chī tài lěng de dōngxi.) — Đừng ăn đồ quá lạnh.\n6. 一天吃三次，一次两片。(Yì tiān chī sān cì, yí cì liǎng piàn.) — Ngày uống ba lần, mỗi lần hai viên.\n\n## Ghi chú ngữ pháp\n别 + động từ là cách nói đừng làm gì, lịch sự hơn thì thêm 请: 请别抽烟。Động từ năng nguyện 要 ở đây mang nghĩa cần phải, phủ định của nó là 不用 chứ không phải 不要.\n\n## Luyện tập\nĐóng vai hội thoại giữa bệnh nhân và bác sĩ dài ít nhất tám lượt lời.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-06.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-06.mp3', 6, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(19, 2, 'du-lich-dat-phong', 'Bài 7: Du lịch và đặt phòng khách sạn',
 'Lên kế hoạch du lịch với 打算, đặt phòng khách sạn và nhờ vả người khác bằng giới từ 帮.',
 '## Mục tiêu bài học\nLên kế hoạch cho một chuyến đi và đặt phòng khách sạn bằng tiếng Trung.\n\n## Mẫu câu trọng tâm\n1. 我打算下个月去北京旅游。(Wǒ dǎsuàn xià ge yuè qù Běijīng lǚyóu.) — Tôi định tháng sau đi du lịch Bắc Kinh.\n2. 我想订一个房间。(Wǒ xiǎng dìng yí ge fángjiān.) — Tôi muốn đặt một phòng.\n3. 从二十号到二十三号，三天。(Cóng èrshí hào dào èrshísān hào, sān tiān.) — Từ ngày 20 đến ngày 23, ba ngày.\n4. 一个晚上多少钱？(Yí ge wǎnshang duōshao qián?) — Một đêm bao nhiêu tiền?\n5. 请帮我叫一辆出租车。(Qǐng bāng wǒ jiào yí liàng chūzūchē.) — Làm ơn gọi giúp tôi một chiếc taxi.\n6. 长城真漂亮！(Chángchéng zhēn piàoliang!) — Vạn Lý Trường Thành đẹp thật!\n\n## Ghi chú ngữ pháp\n打算 diễn tả dự định đã cân nhắc, khác với 想 chỉ mong muốn. Cấu trúc nhờ vả: 帮 + người + động từ, ví dụ 帮我看一下 (xem giúp tôi một chút). Động từ lặp lại như 看一下, 试试 làm câu nói mềm và lịch sự hơn.\n\n## Luyện tập\nViết lịch trình ba ngày cho chuyến du lịch mơ ước bằng tiếng Trung.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-07.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-07.mp3', 7, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(20, 2, 'dien-thoai-hen-gap', 'Bài 8: Gọi điện thoại và hẹn gặp',
 'Gọi điện, nhắn lại lời nhắn, hẹn giờ gặp mặt và dùng 正在 để nói hành động đang diễn ra.',
 '## Mục tiêu bài học\nGọi điện thoại bằng tiếng Trung và hẹn gặp bạn bè.\n\n## Mẫu câu trọng tâm\n1. 喂，你好，请问王老师在吗？(Wéi, nǐ hǎo, qǐngwèn Wáng lǎoshī zài ma?) — Alô, xin hỏi thầy Vương có ở đó không ạ?\n2. 他正在开会，你等一下。(Tā zhèngzài kāihuì, nǐ děng yíxià.) — Thầy đang họp, bạn đợi một chút nhé.\n3. 我晚上给你打电话。(Wǒ wǎnshang gěi nǐ dǎ diànhuà.) — Tối tôi sẽ gọi điện cho bạn.\n4. 我们几点见面？(Wǒmen jǐ diǎn jiànmiàn?) — Mấy giờ chúng ta gặp nhau?\n5. 明天下午三点，在咖啡店门口。(Míngtiān xiàwǔ sān diǎn, zài kāfēidiàn ménkǒu.) — 3 giờ chiều mai, ở trước cửa quán cà phê.\n6. 我们一起去，好吗？(Wǒmen yìqǐ qù, hǎo ma?) — Chúng ta cùng đi nhé?\n\n## Ghi chú ngữ pháp\n正在 + động từ + 呢 diễn tả hành động đang diễn ra: 他正在吃饭呢。Giới từ 给 chỉ đối tượng nhận hành động và luôn đứng trước động từ: 给妈妈打电话, không nói 打电话给妈妈 theo kiểu tiếng Việt.\n\n## Luyện tập\nViết một cuộc gọi điện hẹn bạn đi xem phim, dài khoảng mười lượt lời.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-08.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-08.mp3', 8, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(21, 2, 'thoi-tiet-ke-hoach', 'Bài 9: Thời tiết và kế hoạch cuối tuần',
 'Dự đoán thời tiết bằng 会, mô tả hai đặc điểm cùng lúc với 又…又… và đặt điều kiện với 如果…就….',
 '## Mục tiêu bài học\nDự đoán thời tiết và lên kế hoạch cuối tuần theo điều kiện thời tiết.\n\n## Mẫu câu trọng tâm\n1. 天气预报说明天会下雨。(Tiānqì yùbào shuō míngtiān huì xiàyǔ.) — Dự báo thời tiết nói mai sẽ mưa.\n2. 今天又闷又热。(Jīntiān yòu mēn yòu rè.) — Hôm nay vừa oi vừa nóng.\n3. 如果不下雨，我们就去公园。(Rúguǒ bú xiàyǔ, wǒmen jiù qù gōngyuán.) — Nếu không mưa thì chúng ta đi công viên.\n4. 周末你打算做什么？(Zhōumò nǐ dǎsuàn zuò shénme?) — Cuối tuần bạn định làm gì?\n5. 北京的冬天比河内冷多了。(Běijīng de dōngtiān bǐ Hénèi lěng duō le.) — Mùa đông Bắc Kinh lạnh hơn Hà Nội nhiều.\n\n## Ghi chú ngữ pháp\n会 ngoài nghĩa biết làm còn dùng để dự đoán khả năng xảy ra trong tương lai: 明天会更冷。Cấu trúc 又…又… nối hai tính từ cùng loại. Trong câu điều kiện, vế sau gần như luôn có 就 làm từ hô ứng.\n\n## Luyện tập\nViết ba câu điều kiện 如果…就… về kế hoạch cuối tuần của bạn.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-09.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-09.mp3', 9, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(22, 2, 'truong-lop-kiem-tra', 'Bài 10: Lớp học và kỳ kiểm tra',
 'Nói về việc thi cử, dùng bổ ngữ trạng thái với 得, cấu trúc 快要…了 và cặp từ 虽然…但是….',
 '## Mục tiêu bài học\nNói về bài kiểm tra, nhận xét việc học của bạn bè và động viên nhau.\n\n## Mẫu câu trọng tâm\n1. 快要考试了，我很紧张。(Kuàiyào kǎoshì le, wǒ hěn jǐnzhāng.) — Sắp thi rồi, tôi rất căng thẳng.\n2. 他汉语说得很流利。(Tā Hànyǔ shuō de hěn liúlì.) — Cậu ấy nói tiếng Trung rất trôi chảy.\n3. 我写汉字写得不太好。(Wǒ xiě Hànzì xiě de bú tài hǎo.) — Tôi viết chữ Hán không được đẹp lắm.\n4. 虽然很难，但是很有意思。(Suīrán hěn nán, dànshì hěn yǒu yìsi.) — Tuy khó nhưng rất thú vị.\n5. 你要努力学习。(Nǐ yào nǔlì xuéxí.) — Bạn phải cố gắng học.\n\n## Ghi chú ngữ pháp\nBổ ngữ trạng thái: Động từ + 得 + tính từ. Nếu có tân ngữ, phải lặp lại động từ: 他说汉语说得很好, hoặc đảo tân ngữ lên trước: 他汉语说得很好. Cấu trúc 快要…了 và 就要…了 đều nói sắp xảy ra, nhưng 就要…了 dùng được với mốc thời gian cụ thể.\n\n## Luyện tập\nNhận xét năm việc bạn làm giỏi hoặc chưa giỏi bằng năm câu có 得.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-10.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-10.mp3', 10, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(23, 2, 'mieu-ta-nguoi', 'Bài 11: Miêu tả người và tính cách',
 'Miêu tả ngoại hình bằng 长得, dùng 有点儿 khi nhận xét nhẹ nhàng và so sánh nhất với 最.',
 '## Mục tiêu bài học\nMiêu tả ngoại hình, tính cách của người thân và bạn bè.\n\n## Từ vựng trọng tâm\n高 gāo (cao), 矮 ǎi (thấp), 胖 pàng (mập), 瘦 shòu (gầy), 漂亮 piàoliang (xinh đẹp), 帅 shuài (đẹp trai), 聪明 cōngming (thông minh), 认真 rènzhēn (nghiêm túc), 热情 rèqíng (nhiệt tình).\n\n## Mẫu câu trọng tâm\n1. 他长得很像他爸爸。(Tā zhǎng de hěn xiàng tā bàba.) — Cậu ấy trông rất giống bố.\n2. 我姐姐又高又漂亮。(Wǒ jiějie yòu gāo yòu piàoliang.) — Chị tôi vừa cao vừa xinh.\n3. 他有点儿胖，但是很可爱。(Tā yǒudiǎnr pàng, dànshì hěn kě''ài.) — Cậu ấy hơi mập nhưng rất đáng yêu.\n4. 她是我们班最认真的学生。(Tā shì wǒmen bān zuì rènzhēn de xuésheng.) — Cô ấy là học sinh chăm chỉ nhất lớp.\n5. 我的同事对我很热情。(Wǒ de tóngshì duì wǒ hěn rèqíng.) — Đồng nghiệp rất nhiệt tình với tôi.\n\n## Ghi chú ngữ pháp\n长得 chuyên dùng để miêu tả ngoại hình bẩm sinh. 有点儿 đứng trước tính từ và mang sắc thái không hài lòng, nên hầu như không nói 有点儿漂亮. Cấu trúc so sánh nhất: 最 + tính từ + 的 + danh từ.\n\n## Luyện tập\nMiêu tả ba người trong gia đình bạn, mỗi người ít nhất ba câu.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-11.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-11.mp3', 11, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(24, 2, 'on-tap-tong-hop-hsk2', 'Bài 12: Ôn tập tổng hợp HSK 2',
 'Tổng kết trợ từ 了, 过 và cấu trúc 正在…呢, hệ thống lại ngữ pháp HSK 2 và luyện một đề thi hoàn chỉnh.',
 '## Mục tiêu bài học\nHệ thống lại toàn bộ ngữ pháp HSK 2 và luyện đề thi thật.\n\n## Ba trợ từ dễ nhầm nhất\n1. 了 chỉ hành động đã hoàn thành: 我吃了饭。(Wǒ chī le fàn.) — Tôi ăn cơm rồi.\n2. 过 chỉ kinh nghiệm từng trải qua: 我去过中国。(Wǒ qù guo Zhōngguó.) — Tôi từng đi Trung Quốc.\n3. 正在…呢 chỉ hành động đang diễn ra: 他正在睡觉呢。(Tā zhèngzài shuìjiào ne.) — Cậu ấy đang ngủ.\n\n## Những cấu trúc bắt buộc nhớ\nCâu so sánh với 比, bổ ngữ trạng thái với 得, câu điều kiện 如果…就…, cặp nhân quả 因为…所以…, cặp nhượng bộ 虽然…但是…, cấu trúc 从…到… và giới từ 离.\n\n## Cấu trúc đề thi HSK 2\nĐề gồm 35 câu nghe và 25 câu đọc, tổng 200 điểm, đạt 120 điểm là qua, thời gian làm bài 55 phút. Đề vẫn có pinyin nhưng vốn từ tăng lên 300 từ.\n\n## Luyện tập\nLàm đề HSK 2 mẫu trong 55 phút, lập danh sách những điểm ngữ pháp còn sai và ôn lại bài tương ứng.',
 'https://cdn.hoctiengtrung.vn/videos/hsk2-bai-12.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk2-bai-12.mp3', 12, 65, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000');

-- ---------------------------------------------------------------------
-- 4. LESSONS - Khoa 3 : HSK 3 trung cap (id 25..32)
-- ---------------------------------------------------------------------
INSERT INTO lessons (id, course_id, slug, title, summary, content, video_url, audio_url, sort_order, estimated_minutes, published, created_at, updated_at) VALUES
(25, 3, 'ke-lai-mot-ngay', 'Bài 1: Kể lại một ngày của bạn',
 'Kể chuỗi sự việc theo trình tự thời gian, dùng 先…然后…最后… và bổ ngữ kết quả 完, 好.',
 '## Mục tiêu bài học\nKể lại một ngày của bạn theo trình tự mạch lạc, không chỉ liệt kê rời rạc.\n\n## Mẫu câu trọng tâm\n1. 我先吃早饭，然后去上班，最后回家做饭。(Wǒ xiān chī zǎofàn, ránhòu qù shàngbān, zuìhòu huí jiā zuò fàn.) — Tôi ăn sáng trước, sau đó đi làm, cuối cùng về nhà nấu cơm.\n2. 我做完作业才睡觉。(Wǒ zuò wán zuòyè cái shuìjiào.) — Làm xong bài tập tôi mới đi ngủ.\n3. 一下班我就回家了。(Yí xiàbān wǒ jiù huí jiā le.) — Vừa tan làm là tôi về nhà ngay.\n4. 今天过得特别快。(Jīntiān guò de tèbié kuài.) — Hôm nay trôi qua đặc biệt nhanh.\n\n## Ghi chú ngữ pháp\nBổ ngữ kết quả đứng ngay sau động từ để nói kết quả của hành động: 看完 (xem xong), 听懂 (nghe hiểu), 找到 (tìm được), 写好 (viết xong xuôi). Cặp 一…就… diễn tả hai việc nối tiếp tức thì. 才 nhấn mạnh muộn hoặc khó khăn, 就 nhấn mạnh sớm và dễ dàng.\n\n## Luyện tập\nViết nhật ký một ngày của bạn dài khoảng 100 chữ Hán, dùng ít nhất ba bổ ngữ kết quả.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-01.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-01.mp3', 1, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(26, 3, 'so-sanh-lua-chon', 'Bài 2: So sánh và đưa ra lựa chọn',
 'Mở rộng câu chữ 比, dùng 跟…一样, 没有 để so sánh và diễn đạt sự lựa chọn với 不如, 更.',
 '## Mục tiêu bài học\nSo sánh nhiều đối tượng và giải thích vì sao bạn chọn phương án nào đó.\n\n## Mẫu câu trọng tâm\n1. 坐高铁比坐飞机方便多了。(Zuò gāotiě bǐ zuò fēijī fāngbiàn duō le.) — Đi tàu cao tốc tiện hơn đi máy bay nhiều.\n2. 我的手机跟你的一样。(Wǒ de shǒujī gēn nǐ de yíyàng.) — Điện thoại của tôi giống hệt của bạn.\n3. 今天没有昨天热。(Jīntiān méiyǒu zuótiān rè.) — Hôm nay không nóng bằng hôm qua.\n4. 这个办法不如那个好。(Zhège bànfǎ bùrú nàge hǎo.) — Cách này không tốt bằng cách kia.\n5. 我觉得红色的更适合你。(Wǒ juéde hóngsè de gèng shìhé nǐ.) — Tôi thấy màu đỏ hợp với bạn hơn.\n\n## Ghi chú ngữ pháp\nBa cách so sánh cần phân biệt rõ: A 比 B + tính từ (hơn), A 跟 B 一样 + tính từ (bằng nhau), A 没有 B + tính từ (kém hơn). Phó từ 更 và 最 dùng được trong câu 比, còn 很 và 太 thì không.\n\n## Luyện tập\nViết đoạn văn so sánh hai thành phố bạn từng sống, dùng đủ ba cấu trúc so sánh trên.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-02.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-02.mp3', 2, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(27, 3, 'kinh-nghiem-qua-khu', 'Bài 3: Kể về kinh nghiệm đã trải qua',
 'Dùng 过 để kể trải nghiệm, cấu trúc nhấn mạnh 是…的 và cách nói khoảng thời gian đã kéo dài.',
 '## Mục tiêu bài học\nKể lại những việc bạn từng làm và nhấn mạnh thời gian, địa điểm, cách thức của sự việc.\n\n## Mẫu câu trọng tâm\n1. 我去过三次上海。(Wǒ qù guo sān cì Shànghǎi.) — Tôi từng đi Thượng Hải ba lần.\n2. 我没吃过北京烤鸭。(Wǒ méi chī guo Běijīng kǎoyā.) — Tôi chưa từng ăn vịt quay Bắc Kinh.\n3. 我是去年来中国的。(Wǒ shì qùnián lái Zhōngguó de.) — Tôi đến Trung Quốc vào năm ngoái.\n4. 他是坐火车去的。(Tā shì zuò huǒchē qù de.) — Anh ấy đi bằng tàu hỏa.\n5. 我学汉语学了两年了。(Wǒ xué Hànyǔ xué le liǎng nián le.) — Tôi học tiếng Trung được hai năm rồi.\n\n## Ghi chú ngữ pháp\nCấu trúc 是…的 dùng khi việc đã xảy ra và người nói muốn nhấn mạnh thời gian, nơi chốn hay phương thức, không nhấn mạnh bản thân sự việc. Bổ ngữ thời lượng đặt sau động từ, nếu có tân ngữ thì lặp lại động từ.\n\n## Luyện tập\nViết năm câu về những nơi bạn từng đến và năm câu về những việc bạn chưa từng làm.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-03.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-03.mp3', 3, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(28, 3, 'suc-khoe-thoi-quen', 'Bài 4: Sức khỏe và thói quen sinh hoạt',
 'Khuyên nhủ người khác, nói về thói quen tốt xấu và dùng câu chữ 把 trong ngữ cảnh sinh hoạt.',
 '## Mục tiêu bài học\nBàn về thói quen sinh hoạt lành mạnh và đưa ra lời khuyên cho bạn bè.\n\n## Mẫu câu trọng tâm\n1. 你应该早点儿睡觉。(Nǐ yīnggāi zǎo diǎnr shuìjiào.) — Bạn nên đi ngủ sớm hơn.\n2. 我每天坚持锻炼半个小时。(Wǒ měi tiān jiānchí duànliàn bàn ge xiǎoshí.) — Ngày nào tôi cũng kiên trì tập thể dục nửa tiếng.\n3. 别把工作带回家。(Bié bǎ gōngzuò dài huí jiā.) — Đừng mang công việc về nhà.\n4. 请把药放在桌子上。(Qǐng bǎ yào fàng zài zhuōzi shàng.) — Làm ơn đặt thuốc lên bàn.\n5. 熬夜对身体不好。(Áoyè duì shēntǐ bù hǎo.) — Thức khuya không tốt cho sức khỏe.\n\n## Ghi chú ngữ pháp\nCâu chữ 把 có công thức: Chủ ngữ + 把 + tân ngữ xác định + động từ + thành phần khác. Động từ trong câu 把 không bao giờ đứng trơ trọi, bắt buộc có bổ ngữ, trợ từ 了 hoặc thành phần lặp phía sau.\n\n## Luyện tập\nViết năm lời khuyên về sức khỏe cho một người bạn hay thức khuya, dùng ít nhất hai câu 把.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-04.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-04.mp3', 4, 60, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(29, 3, 'hoc-tap-ky-nang', 'Bài 5: Học tập và rèn kỹ năng',
 'Bàn về phương pháp học, dùng bổ ngữ khả năng 听得懂, 看不完 và các liên từ 不但…而且….',
 '## Mục tiêu bài học\nTrao đổi về phương pháp học tiếng Trung và tự đánh giá khả năng của mình.\n\n## Mẫu câu trọng tâm\n1. 老师说得慢，我听得懂。(Lǎoshī shuō de màn, wǒ tīng de dǒng.) — Cô giáo nói chậm nên tôi nghe hiểu được.\n2. 这本书太厚了，一天看不完。(Zhè běn shū tài hòu le, yì tiān kàn bu wán.) — Sách này dày quá, một ngày đọc không hết.\n3. 汉语不但有意思，而且很有用。(Hànyǔ búdàn yǒu yìsi, érqiě hěn yǒuyòng.) — Tiếng Trung không những thú vị mà còn rất hữu ích.\n4. 只要每天练习，就一定会进步。(Zhǐyào měi tiān liànxí, jiù yídìng huì jìnbù.) — Chỉ cần luyện mỗi ngày là nhất định sẽ tiến bộ.\n5. 遇到生词就查词典。(Yùdào shēngcí jiù chá cídiǎn.) — Gặp từ mới thì tra từ điển.\n\n## Ghi chú ngữ pháp\nBổ ngữ khả năng chèn 得 hoặc 不 giữa động từ và bổ ngữ kết quả: 看得完 (đọc kịp hết) và 看不完 (không đọc hết nổi). Đây là điểm ngữ pháp phân biệt rõ HSK 3 với HSK 2.\n\n## Luyện tập\nViết mười câu bổ ngữ khả năng về những việc bạn làm được và không làm được trong tiếng Trung.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-05.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-05.mp3', 5, 65, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(30, 3, 'van-hoa-le-hoi', 'Bài 6: Văn hóa và lễ hội Trung Quốc',
 'Tìm hiểu Tết Nguyên đán, Trung thu, phong tục tặng quà và học cách chúc mừng bằng tiếng Trung.',
 '## Mục tiêu bài học\nHiểu các lễ hội lớn của Trung Quốc và biết nói lời chúc phù hợp với từng dịp.\n\n## Các lễ hội quan trọng\n春节 Chūnjié — Tết Nguyên đán, dịp đoàn viên lớn nhất trong năm, người ta dán câu đối đỏ và lì xì 红包.\n中秋节 Zhōngqiūjié — Tết Trung thu, ăn bánh trung thu 月饼 và ngắm trăng.\n国庆节 Guóqìngjié — Quốc khánh mùng 1 tháng 10, kỳ nghỉ dài gọi là 黄金周.\n\n## Mẫu câu trọng tâm\n1. 春节快乐！恭喜发财！(Chūnjié kuàilè! Gōngxǐ fācái!) — Chúc mừng năm mới! Chúc phát tài!\n2. 中国人过春节的时候喜欢吃饺子。(Zhōngguó rén guò Chūnjié de shíhou xǐhuan chī jiǎozi.) — Người Trung Quốc thích ăn sủi cảo dịp Tết.\n3. 送礼物的时候不要送钟。(Sòng lǐwù de shíhou búyào sòng zhōng.) — Khi tặng quà đừng tặng đồng hồ treo tường.\n\n## Ghi chú văn hóa\nSố 8 được ưa chuộng vì 八 đọc gần với 发 (phát tài), còn số 4 bị kiêng vì 四 đồng âm với 死. Tặng đồng hồ treo tường 送钟 đồng âm với 送终 nên bị coi là điềm gở.\n\n## Luyện tập\nViết một tấm thiệp chúc Tết bằng tiếng Trung gửi cho giáo viên của bạn.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-06.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-06.mp3', 6, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(31, 3, 'cong-nghe-internet', 'Bài 7: Công nghệ và Internet',
 'Từ vựng về điện thoại thông minh, mạng xã hội, thanh toán điện tử và cách nói gặp sự cố kỹ thuật.',
 '## Mục tiêu bài học\nSử dụng tiếng Trung trong đời sống số: nhắn tin, thanh toán và xử lý sự cố mạng.\n\n## Từ vựng trọng tâm\n上网 shàngwǎng (lên mạng), 网站 wǎngzhàn (trang web), 微信 Wēixìn (WeChat), 支付宝 Zhīfùbǎo (Alipay), 扫码 sǎomǎ (quét mã), 密码 mìmǎ (mật khẩu), 充电 chōngdiàn (sạc pin), 死机 sǐjī (treo máy).\n\n## Mẫu câu trọng tâm\n1. 请扫一下这个二维码。(Qǐng sǎo yíxià zhège èrwéimǎ.) — Xin quét mã QR này.\n2. 我用微信支付，可以吗？(Wǒ yòng Wēixìn zhīfù, kěyǐ ma?) — Tôi trả bằng WeChat được không?\n3. 这里的网络信号不太好。(Zhèlǐ de wǎngluò xìnhào bú tài hǎo.) — Sóng mạng ở đây không tốt lắm.\n4. 我的手机没电了。(Wǒ de shǒujī méi diàn le.) — Điện thoại tôi hết pin rồi.\n5. 密码输错了三次。(Mìmǎ shū cuò le sān cì.) — Nhập sai mật khẩu ba lần rồi.\n\n## Ghi chú ngữ pháp\nGiới từ 用 chỉ công cụ và luôn đứng trước động từ: 用手机付钱. Bổ ngữ kết quả 错 và 对 rất hay gặp trong ngữ cảnh này: 说错, 写错, 猜对.\n\n## Luyện tập\nViết đoạn hội thoại mua cà phê và thanh toán bằng quét mã tại quán ở Trung Quốc.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-07.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-07.mp3', 7, 55, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(32, 3, 'on-tap-hsk3', 'Bài 8: Ôn tập và luyện đề HSK 3',
 'Tổng kết câu chữ 把, câu bị động, bổ ngữ các loại và làm quen phần viết chữ Hán trong đề HSK 3.',
 '## Mục tiêu bài học\nHệ thống ngữ pháp HSK 3 và làm quen phần thi viết vốn không có ở HSK 1 và HSK 2.\n\n## Hệ thống bổ ngữ cần nhớ\n1. Bổ ngữ kết quả: 听懂, 做完, 找到.\n2. Bổ ngữ khả năng: 听得懂, 做不完, 找不到.\n3. Bổ ngữ trạng thái: 说得很流利.\n4. Bổ ngữ xu hướng: 走进来, 拿出去, 站起来.\n\n## Câu chữ 把 và câu bị động\n把: 我把窗户关上了。(Wǒ bǎ chuānghu guān shàng le.) — Tôi đã đóng cửa sổ lại.\n被: 我的自行车被人骑走了。(Wǒ de zìxíngchē bèi rén qí zǒu le.) — Xe đạp của tôi bị người ta lấy đi mất.\n\n## Cấu trúc đề thi HSK 3\nĐề gồm 40 câu nghe, 30 câu đọc và 10 câu viết, tổng 300 điểm, đạt 180 điểm là qua, thời gian 90 phút. Từ cấp độ này đề không còn pinyin, thí sinh phải viết được chữ Hán.\n\n## Luyện tập\nLàm một đề HSK 3 hoàn chỉnh trong 90 phút và chép tay 20 chữ Hán bị sai nhiều nhất.',
 'https://cdn.hoctiengtrung.vn/videos/hsk3-bai-08.mp4', 'https://cdn.hoctiengtrung.vn/audio/hsk3-bai-08.mp3', 8, 70, b'1', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000');

-- ---------------------------------------------------------------------
-- 5. LESSONS - Khoa 4, 5, 6 : de cuong chua xuat ban (id 33..44)
-- ---------------------------------------------------------------------
INSERT INTO lessons (id, course_id, slug, title, summary, content, video_url, audio_url, sort_order, estimated_minutes, published, created_at, updated_at) VALUES
(33, 4, 'bay-to-quan-diem', 'Bài 1: Bày tỏ quan điểm và tranh luận nhẹ nhàng',
 'Nêu ý kiến, đồng tình và phản đối lịch sự bằng các mẫu câu HSK 4 thường gặp trong hội thoại công sở.',
 '## Mục tiêu bài học\nNêu quan điểm cá nhân rõ ràng, biết đồng tình và phản đối một cách lịch sự.\n\n## Mẫu câu trọng tâm\n1. 在我看来，这个方案更合适。(Zài wǒ kànlái, zhège fāng''àn gèng héshì.) — Theo tôi thấy, phương án này phù hợp hơn.\n2. 我完全同意你的看法。(Wǒ wánquán tóngyì nǐ de kànfǎ.) — Tôi hoàn toàn đồng ý với ý kiến của bạn.\n3. 我有不同的意见。(Wǒ yǒu bùtóng de yìjiàn.) — Tôi có ý kiến khác.\n4. 与其等待，不如现在就开始。(Yǔqí děngdài, bùrú xiànzài jiù kāishǐ.) — Thay vì chờ đợi, chi bằng bắt đầu ngay bây giờ.\n5. 无论结果怎么样，我们都要努力。(Wúlùn jiéguǒ zěnmeyàng, wǒmen dōu yào nǔlì.) — Bất kể kết quả thế nào, chúng ta đều phải cố gắng.\n\n## Ghi chú ngữ pháp\nCác cặp liên từ HSK 4 rất hay xuất hiện trong đề thi: 无论…都…, 与其…不如…, 即使…也…, 只有…才…. Điểm chung là vế sau luôn có từ hô ứng 都, 也 hoặc 才.\n\n## Luyện tập\nChọn một chủ đề tranh luận và viết ba câu ủng hộ, ba câu phản đối.',
 NULL, NULL, 1, 70, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(34, 4, 'cong-viec-phong-van', 'Bài 2: Công việc và phỏng vấn xin việc',
 'Từ vựng tuyển dụng, cách trình bày kinh nghiệm và trả lời những câu hỏi phỏng vấn phổ biến.',
 '## Mục tiêu bài học\nChuẩn bị một buổi phỏng vấn xin việc hoàn toàn bằng tiếng Trung.\n\n## Từ vựng trọng tâm\n简历 jiǎnlì (sơ yếu lý lịch), 应聘 yìngpìn (ứng tuyển), 面试 miànshì (phỏng vấn), 经验 jīngyàn (kinh nghiệm), 能力 nénglì (năng lực), 工资 gōngzī (lương), 加班 jiābān (làm thêm giờ), 专业 zhuānyè (chuyên ngành).\n\n## Mẫu câu trọng tâm\n1. 我想应聘贵公司的市场专员。(Wǒ xiǎng yìngpìn guì gōngsī de shìchǎng zhuānyuán.) — Tôi muốn ứng tuyển vị trí nhân viên marketing của quý công ty.\n2. 我有三年相关工作经验。(Wǒ yǒu sān nián xiāngguān gōngzuò jīngyàn.) — Tôi có ba năm kinh nghiệm liên quan.\n3. 我的优点是认真负责。(Wǒ de yōudiǎn shì rènzhēn fùzé.) — Ưu điểm của tôi là nghiêm túc và có trách nhiệm.\n4. 我希望能有机会为公司做贡献。(Wǒ xīwàng néng yǒu jīhuì wèi gōngsī zuò gòngxiàn.) — Tôi hy vọng có cơ hội đóng góp cho công ty.\n\n## Luyện tập\nViết bản giới thiệu bản thân 90 giây bằng tiếng Trung dùng cho vòng phỏng vấn đầu tiên.',
 NULL, NULL, 2, 70, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(35, 4, 'moi-truong-xa-hoi', 'Bài 3: Môi trường và các vấn đề xã hội',
 'Từ vựng về ô nhiễm, tiết kiệm năng lượng, dân số và cách nêu nguyên nhân, hậu quả, giải pháp.',
 '## Mục tiêu bài học\nThảo luận các vấn đề xã hội quen thuộc trong đề thi HSK 4 và bài thi nói.\n\n## Từ vựng trọng tâm\n环境 huánjìng (môi trường), 污染 wūrǎn (ô nhiễm), 空气 kōngqì (không khí), 垃圾 lājī (rác), 节约 jiéyuē (tiết kiệm), 资源 zīyuán (tài nguyên), 保护 bǎohù (bảo vệ), 影响 yǐngxiǎng (ảnh hưởng).\n\n## Mẫu câu trọng tâm\n1. 空气污染越来越严重了。(Kōngqì wūrǎn yuèláiyuè yánzhòng le.) — Ô nhiễm không khí ngày càng nghiêm trọng.\n2. 保护环境，人人有责。(Bǎohù huánjìng, rénrén yǒu zé.) — Bảo vệ môi trường là trách nhiệm của mọi người.\n3. 随着经济的发展，垃圾也越来越多。(Suízhe jīngjì de fāzhǎn, lājī yě yuèláiyuè duō.) — Cùng với sự phát triển kinh tế, rác thải cũng ngày càng nhiều.\n4. 这对我们的生活影响很大。(Zhè duì wǒmen de shēnghuó yǐngxiǎng hěn dà.) — Điều này ảnh hưởng rất lớn tới cuộc sống của chúng ta.\n\n## Ghi chú ngữ pháp\nCấu trúc 越来越 + tính từ diễn tả mức độ tăng dần theo thời gian, còn 越…越… nêu quan hệ tỉ lệ thuận giữa hai vế: 雨越下越大。\n\n## Luyện tập\nViết đoạn văn 80 chữ nêu một vấn đề môi trường ở nơi bạn sống và đề xuất hai giải pháp.',
 NULL, NULL, 3, 70, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(36, 4, 'doc-hieu-van-ban-dai', 'Bài 4: Kỹ năng đọc hiểu văn bản dài',
 'Chiến thuật đọc lướt, đoán nghĩa từ mới qua bộ thủ và ngữ cảnh, quản lý thời gian phần đọc HSK 4.',
 '## Mục tiêu bài học\nĐọc nhanh một đoạn văn 300 chữ và trả lời đúng câu hỏi mà không cần hiểu từng chữ.\n\n## Ba bước đọc hiệu quả\n1. Đọc câu hỏi trước để biết cần tìm thông tin gì.\n2. Đọc lướt câu đầu và câu cuối mỗi đoạn vì ý chính thường nằm ở đó.\n3. Khoanh vùng từ khóa rồi mới đọc kỹ đoạn chứa đáp án.\n\n## Đoán nghĩa từ mới\nBộ thủ cho biết trường nghĩa của chữ: bộ 氵 liên quan tới nước (河, 洗, 汤), bộ 木 liên quan tới cây gỗ (树, 桌, 椅), bộ 心 và 忄 liên quan tới cảm xúc (想, 忙, 快). Kết hợp bộ thủ với ngữ cảnh, bạn đoán được phần lớn từ mới trong đề.\n\n## Ví dụ minh họa\n虽然他的汉语水平不高，但是通过上下文，他还是猜出了这个词的意思。(Suīrán tā de Hànyǔ shuǐpíng bù gāo, dànshì tōngguò shàngxiàwén, tā háishi cāi chū le zhège cí de yìsi.) — Tuy trình độ tiếng Trung chưa cao nhưng nhờ ngữ cảnh, anh ấy vẫn đoán ra nghĩa của từ này.\n\n## Luyện tập\nMỗi ngày đọc một bài 300 chữ, đặt đồng hồ 6 phút và ghi lại 5 từ mới đoán được nghĩa.',
 NULL, NULL, 4, 65, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(37, 5, 'thanh-ngu-thong-dung', 'Bài 1: Thành ngữ bốn chữ thông dụng',
 'Học 20 thành ngữ HSK 5 hay gặp nhất, hiểu điển tích và cách dùng đúng ngữ cảnh trong văn viết.',
 '## Mục tiêu bài học\nDùng đúng thành ngữ bốn chữ trong bài viết và bài nói ở trình độ cao cấp.\n\n## Một số thành ngữ trọng tâm\n1. 入乡随俗 rù xiāng suí sú — nhập gia tùy tục.\n2. 一举两得 yì jǔ liǎng dé — một công đôi việc.\n3. 半途而废 bàn tú ér fèi — bỏ dở giữa chừng.\n4. 三心二意 sān xīn èr yì — ba lòng bốn dạ, không chuyên tâm.\n5. 名副其实 míng fù qí shí — danh xứng với thực.\n\n## Ví dụ trong câu\n到了中国就要入乡随俗，尊重当地的习惯。(Dào le Zhōngguó jiù yào rù xiāng suí sú, zūnzhòng dāngdì de xíguàn.) — Đến Trung Quốc thì phải nhập gia tùy tục, tôn trọng tập quán địa phương.\n学习最怕半途而废。(Xuéxí zuì pà bàn tú ér fèi.) — Việc học sợ nhất là bỏ dở giữa chừng.\n\n## Lưu ý sử dụng\nThành ngữ hầu hết mang sắc thái trang trọng, hợp với văn viết và bài phát biểu. Trong hội thoại đời thường, dùng quá nhiều thành ngữ sẽ nghe gượng gạo và thiếu tự nhiên.\n\n## Luyện tập\nĐặt câu với 10 thành ngữ, mỗi câu gắn với một tình huống thực tế của bạn.',
 NULL, NULL, 1, 75, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(38, 5, 'kinh-te-thuong-mai', 'Bài 2: Tiếng Trung kinh tế và thương mại',
 'Từ vựng đàm phán, hợp đồng, báo giá và các mẫu câu email thương mại chuẩn mực.',
 '## Mục tiêu bài học\nĐọc hiểu tin kinh tế và trao đổi công việc thương mại bằng tiếng Trung.\n\n## Từ vựng trọng tâm\n市场 shìchǎng (thị trường), 投资 tóuzī (đầu tư), 成本 chéngběn (chi phí), 利润 lìrùn (lợi nhuận), 合同 hétong (hợp đồng), 谈判 tánpàn (đàm phán), 报价 bàojià (báo giá), 出口 chūkǒu (xuất khẩu), 进口 jìnkǒu (nhập khẩu).\n\n## Mẫu câu trọng tâm\n1. 请贵公司尽快提供报价单。(Qǐng guì gōngsī jǐnkuài tígōng bàojiàdān.) — Kính đề nghị quý công ty sớm gửi bảng báo giá.\n2. 我们希望能够长期合作。(Wǒmen xīwàng nénggòu chángqī hézuò.) — Chúng tôi mong có thể hợp tác lâu dài.\n3. 这个价格已经是最低的了。(Zhège jiàgé yǐjīng shì zuì dī de le.) — Mức giá này đã là thấp nhất rồi.\n4. 合同一式两份，双方各执一份。(Hétong yí shì liǎng fèn, shuāngfāng gè zhí yí fèn.) — Hợp đồng lập thành hai bản, mỗi bên giữ một bản.\n\n## Luyện tập\nViết một email thương mại 150 chữ hỏi giá và đề nghị hợp tác với đối tác Trung Quốc.',
 NULL, NULL, 2, 75, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(39, 5, 'van-hoc-bao-chi', 'Bài 3: Văn học và báo chí',
 'Đọc bản tin, phân biệt văn phong khẩu ngữ với văn viết và làm quen các cấu trúc thư diện ngữ.',
 '## Mục tiêu bài học\nĐọc được bản tin tiếng Trung và nhận ra sự khác nhau giữa khẩu ngữ với văn viết.\n\n## Khẩu ngữ và văn viết\nKhẩu ngữ 因为…所以… tương ứng văn viết 由于…因此…\nKhẩu ngữ 虽然…但是… tương ứng văn viết 尽管…然而…\nKhẩu ngữ 关于这件事 tương ứng văn viết 就此事而言\n\n## Ví dụ bản tin\n据报道，该项目将于明年正式启动，预计投资总额超过十亿元。(Jù bàodào, gāi xiàngmù jiāng yú míngnián zhèngshì qǐdòng, yùjì tóuzī zǒng''é chāoguò shí yì yuán.) — Theo tin đã đưa, dự án sẽ chính thức khởi động vào năm sau, tổng vốn đầu tư dự kiến vượt một tỷ tệ.\n\n## Ghi chú ngôn ngữ\nVăn viết báo chí dùng nhiều từ đơn âm tiết cổ: 该 thay cho 这个, 于 thay cho 在, 将 thay cho 会, 均 thay cho 都. Nắm nhóm từ này giúp tốc độ đọc tăng lên rõ rệt.\n\n## Luyện tập\nMỗi tuần đọc ba bản tin ngắn và viết lại nội dung bằng khẩu ngữ của riêng bạn.',
 NULL, NULL, 3, 75, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(40, 5, 'tranh-luan-thuyet-trinh', 'Bài 4: Tranh luận và thuyết trình',
 'Xây dựng dàn ý bài thuyết trình, dùng từ nối mạch lạc và phản biện quan điểm đối phương.',
 '## Mục tiêu bài học\nTrình bày một bài nói 5 phút có mở bài, thân bài, kết luận rõ ràng.\n\n## Bộ từ nối cần thuộc\nMở đầu: 首先, 第一, 众所周知\nTriển khai: 其次, 另外, 不仅如此, 举个例子来说\nChuyển ý: 然而, 相反, 与此相比\nKết luận: 总之, 综上所述, 因此\n\n## Mẫu câu trọng tâm\n1. 首先，我想谈谈这个问题的背景。(Shǒuxiān, wǒ xiǎng tántan zhège wèntí de bèijǐng.) — Trước tiên, tôi muốn nói về bối cảnh của vấn đề này.\n2. 综上所述，我认为这个方案值得考虑。(Zōng shàng suǒ shù, wǒ rènwéi zhège fāng''àn zhíde kǎolǜ.) — Tóm lại, tôi cho rằng phương án này đáng cân nhắc.\n3. 我理解你的观点，不过我想补充一点。(Wǒ lǐjiě nǐ de guāndiǎn, búguò wǒ xiǎng bǔchōng yìdiǎn.) — Tôi hiểu quan điểm của bạn, nhưng tôi muốn bổ sung một ý.\n\n## Luyện tập\nChuẩn bị bài thuyết trình 5 phút về chủ đề học ngoại ngữ, dùng ít nhất tám từ nối ở trên.',
 NULL, NULL, 4, 80, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(41, 6, 'van-viet-trang-trong', 'Bài 1: Văn viết trang trọng',
 'Chuyển đổi khẩu ngữ sang văn phong trang trọng, viết công văn, thư mời và báo cáo ngắn.',
 '## Mục tiêu bài học\nViết được văn bản trang trọng đúng chuẩn mực hành chính Trung Quốc.\n\n## Đặc điểm văn phong trang trọng\nCâu dài nhiều tầng, dùng nhiều kết cấu bốn chữ, hạn chế trợ từ ngữ khí, ưu tiên từ đơn âm tiết gốc văn ngôn và thể bị động khách quan.\n\n## Ví dụ chuyển đổi\nKhẩu ngữ: 我们下星期要开一个会，请你来参加。\nVăn viết: 兹定于下周召开会议，敬请拨冗出席。(Zī dìng yú xià zhōu zhàokāi huìyì, jìng qǐng bōróng chūxí.) — Nay định tổ chức hội nghị vào tuần sau, kính mời quý vị dành thời gian tham dự.\n\n## Các mẫu thường dùng\n特此通知 tècǐ tōngzhī — nay xin thông báo.\n如有疑问，请与我们联系 rú yǒu yíwèn, qǐng yǔ wǒmen liánxì — nếu có thắc mắc, xin liên hệ với chúng tôi.\n此致敬礼 cǐ zhì jìnglǐ — trân trọng kính chào, dùng cuối thư.\n\n## Luyện tập\nViết một thư mời họp bằng văn phong trang trọng, độ dài khoảng 150 chữ.',
 NULL, NULL, 1, 85, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(42, 6, 'han-ngu-co-dien-co', 'Bài 2: Hán ngữ cổ và điển cố trong tiếng Trung hiện đại',
 'Nhận diện thành phần văn ngôn còn sống trong tiếng Trung hiện đại và hiểu điển cố sau mỗi thành ngữ.',
 '## Mục tiêu bài học\nHiểu lớp trầm tích văn ngôn còn hiện diện dày đặc trong tiếng Trung viết hôm nay.\n\n## Hư từ văn ngôn còn dùng\n之 thay cho 的, 其 thay cho 他的, 者 chỉ người hoặc sự vật, 也 và 矣 làm trợ từ cuối câu, 乃 mang nghĩa chính là.\nVí dụ: 学而时习之，不亦说乎。(Xué ér shí xí zhī, bú yì yuè hū.) — Học rồi thường xuyên ôn lại, chẳng phải là niềm vui sao.\n\n## Điển cố phía sau thành ngữ\n守株待兔 shǒu zhū dài tù bắt nguồn từ chuyện người nông dân thấy thỏ đâm vào gốc cây chết, từ đó bỏ cày mà ngồi chờ, nay chỉ thói ăn may thụ động.\n画蛇添足 huà shé tiān zú kể chuyện vẽ rắn thêm chân, chỉ việc làm thừa hỏng việc.\n\n## Luyện tập\nChọn năm thành ngữ, tra điển cố gốc và viết lại câu chuyện bằng tiếng Trung hiện đại.',
 NULL, NULL, 2, 85, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(43, 6, 'phan-tich-van-ban-hoc-thuat', 'Bài 3: Phân tích văn bản học thuật',
 'Đọc luận văn, tóm tắt luận điểm, nhận diện lập luận và trích dẫn theo quy chuẩn học thuật.',
 '## Mục tiêu bài học\nĐọc và tóm lược một bài báo học thuật tiếng Trung dài 3000 chữ.\n\n## Cấu trúc bài báo học thuật\n摘要 zhāiyào (tóm tắt), 关键词 guānjiàncí (từ khóa), 引言 yǐnyán (dẫn nhập), 研究方法 yánjiū fāngfǎ (phương pháp), 结果与讨论 jiéguǒ yǔ tǎolùn (kết quả và thảo luận), 参考文献 cānkǎo wénxiàn (tài liệu tham khảo).\n\n## Mẫu câu học thuật\n1. 本文旨在探讨汉越语音对比的规律。(Běnwén zhǐ zài tàntǎo Hàn Yuè yǔyīn duìbǐ de guīlǜ.) — Bài viết này nhằm khảo sát quy luật đối chiếu ngữ âm Hán Việt.\n2. 研究结果表明，两者之间存在显著差异。(Yánjiū jiéguǒ biǎomíng, liǎng zhě zhījiān cúnzài xiǎnzhù chāyì.) — Kết quả nghiên cứu cho thấy giữa hai bên tồn tại khác biệt đáng kể.\n3. 综上所述，本文得出以下结论。(Zōng shàng suǒ shù, běnwén déchū yǐxià jiélùn.) — Tóm lại, bài viết rút ra những kết luận sau đây.\n\n## Luyện tập\nTóm tắt một bài báo học thuật tiếng Trung thành 200 chữ, giữ nguyên thuật ngữ chuyên ngành.',
 NULL, NULL, 3, 90, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000'),
(44, 6, 'luyen-thi-hsk6', 'Bài 4: Chiến lược luyện thi HSK 6',
 'Phân tích cấu trúc đề HSK 6, chiến thuật phần nghe, đọc và kỹ thuật viết bài tóm tắt 400 chữ.',
 '## Mục tiêu bài học\nNắm chiến lược làm bài để đạt trên 180 điểm tổng trong kỳ thi HSK 6.\n\n## Cấu trúc đề thi\nNghe 50 câu trong 35 phút, đọc 50 câu trong 50 phút, viết một bài tóm tắt 400 chữ trong 45 phút. Tổng 300 điểm, mỗi phần 100 điểm, 180 điểm là đạt.\n\n## Chiến thuật phần viết\nThí sinh có 10 phút đọc bài gốc khoảng 1000 chữ nhưng không được ghi chép, sau đó 35 phút viết lại thành bài tóm tắt 400 chữ. Bí quyết là ghi nhớ theo bộ khung: nhân vật, thời gian, mâu thuẫn chính, cao trào và kết cục, rồi tự đặt tiêu đề.\n\n## Câu ví dụ trình độ HSK 6\n无论遇到多大的困难，他始终没有放弃自己最初的理想。(Wúlùn yùdào duō dà de kùnnan, tā shǐzhōng méiyǒu fàngqì zìjǐ zuìchū de lǐxiǎng.) — Dù gặp khó khăn lớn đến đâu, anh ấy vẫn không từ bỏ lý tưởng ban đầu của mình.\n\n## Luyện tập\nMỗi tuần làm một đề thi thật trong điều kiện bấm giờ nghiêm ngặt và tự chấm phần viết theo thang điểm chính thức.',
 NULL, NULL, 4, 90, b'0', '2026-01-01 00:00:00.000000', '2026-01-01 00:00:00.000000');

-- ---------------------------------------------------------------------
-- 6. LESSON_GRAMMAR - diem ngu phap khoa 1 (bai 1..12), 3 diem / bai
--    Khong ghi id: de AUTO_INCREMENT tu cap phat.
-- ---------------------------------------------------------------------
INSERT INTO lesson_grammar (lesson_id, title, structure, explanation, example_zh, example_vi, sort_order) VALUES
(1, 'Câu vị ngữ động từ với 是', 'Chủ ngữ + 是 + Danh từ', 'Động từ 是 nối chủ ngữ với danh từ để khẳng định danh tính, nghề nghiệp hoặc quốc tịch. Dạng phủ định là 不是. Lưu ý 是 không dùng trước tính từ, đây là lỗi phổ biến nhất của người Việt mới học.', '我是越南人，他是老师。', 'Tôi là người Việt Nam, anh ấy là giáo viên.', 1),
(1, 'Câu hỏi với trợ từ 吗', 'Câu trần thuật + 吗？', 'Chỉ cần thêm 吗 vào cuối một câu trần thuật là thành câu hỏi có hoặc không, trật tự từ giữ nguyên hoàn toàn. Đây là kiểu câu hỏi đơn giản nhất trong tiếng Trung.', '你好吗？你是学生吗？', 'Bạn khỏe không? Bạn là học sinh phải không?', 2),
(1, 'Hỏi và nói tên với 叫', 'Chủ ngữ + 叫 + tên', 'Động từ 叫 dùng để nói tên gọi. Hỏi tên đầy đủ dùng 你叫什么名字, hỏi họ một cách trang trọng dùng 您贵姓 và trả lời bằng 我姓…', '你叫什么名字？我叫阮明。', 'Bạn tên là gì? Tôi tên là Nguyễn Minh.', 3),
(2, 'Hỏi số lượng nhỏ với 几', '几 + lượng từ + danh từ', 'Từ để hỏi 几 dùng khi người hỏi dự đoán câu trả lời nhỏ hơn 10, luôn phải đi kèm lượng từ. Hỏi ngày, thứ, giờ đều dùng 几.', '今天几号？你有几个哥哥？', 'Hôm nay ngày mấy? Bạn có mấy anh trai?', 1),
(2, 'Hỏi số lượng lớn với 多少', '多少 + (lượng từ) + danh từ', 'Khác với 几, từ 多少 dùng cho số lượng không giới hạn và có thể đứng trực tiếp trước danh từ mà không cần lượng từ. Hỏi giá tiền và số điện thoại đều dùng 多少.', '你的电话号码是多少？这个多少钱？', 'Số điện thoại của bạn là bao nhiêu? Cái này bao nhiêu tiền?', 2),
(2, 'Cách nói ngày tháng và thứ', '年 + 月 + 号 / 星期 + số', 'Trật tự thời gian đi từ đơn vị lớn tới đơn vị nhỏ. Thứ trong tuần ghép 星期 với số từ 一 đến 六, riêng Chủ nhật là 星期天 hoặc 星期日. Câu chỉ ngày tháng có thể lược bỏ động từ 是.', '今天二零二六年一月一号，星期四。', 'Hôm nay ngày 1 tháng 1 năm 2026, thứ Năm.', 3),
(3, 'Câu tồn tại và sở hữu với 有', 'Chủ ngữ + 有 + số lượng + lượng từ + danh từ', 'Động từ 有 diễn tả sở hữu hoặc tồn tại. Dạng phủ định bắt buộc dùng 没有, tuyệt đối không nói 不有.', '我家有四口人，我没有妹妹。', 'Nhà tôi có bốn người, tôi không có em gái.', 1),
(3, 'Trợ từ kết cấu 的 chỉ sở hữu', 'Người sở hữu + 的 + vật sở hữu', 'Trợ từ 的 đứng giữa hai danh từ để chỉ quan hệ sở hữu. Khi nói về người thân hoặc tổ chức gắn bó, 的 thường được lược bỏ: 我妈妈, 我家, 我们学校.', '这是我的书，那是姐姐的手机。', 'Đây là sách của tôi, kia là điện thoại của chị gái.', 2),
(3, 'Lượng từ 口 và 个 khi đếm người', 'Số từ + 口/个 + 人', 'Lượng từ 口 chuyên dùng để đếm nhân khẩu trong một gia đình, còn 个 dùng để đếm người nói chung trong các ngữ cảnh khác.', '我家有五口人，我们班有二十个人。', 'Nhà tôi có năm người, lớp tôi có hai mươi người.', 3),
(4, 'Cách nói giờ với 点 và 分', 'Số + 点 + số + 分', 'Giờ dùng 点, phút dùng 分, rưỡi dùng 半, kém dùng 差. Hỏi giờ dùng 几点. Buổi trong ngày như 上午, 中午, 下午, 晚上 đặt trước số giờ.', '现在下午三点十五分，我们四点半见。', 'Bây giờ 3 giờ 15 chiều, 4 rưỡi chúng ta gặp nhau.', 1),
(4, 'Vị trí của trạng ngữ thời gian', 'Chủ ngữ + thời gian + động từ + tân ngữ', 'Trạng ngữ thời gian bắt buộc đứng trước động từ, khác hẳn tiếng Việt vốn hay đặt ở cuối câu. Có thể chuyển thời gian lên đầu câu để nhấn mạnh.', '我每天七点起床，晚上十一点睡觉。', 'Ngày nào tôi cũng dậy lúc 7 giờ, 11 giờ đêm mới đi ngủ.', 2),
(4, 'Hỏi thời điểm với 什么时候', 'Chủ ngữ + 什么时候 + Động từ', 'Cụm 什么时候 hỏi về thời điểm chung chung, đứng ở vị trí của trạng ngữ thời gian trong câu trả lời, tức là trước động từ.', '你什么时候去中国？我下个月去。', 'Khi nào bạn đi Trung Quốc? Tháng sau tôi đi.', 3),
(5, 'Động từ năng nguyện 想', 'Chủ ngữ + 想 + động từ + tân ngữ', 'Động từ 想 đứng trước động từ chính để nói mong muốn làm việc gì, phủ định là 不想. Khi 想 đứng trước danh từ chỉ người thì mang nghĩa nhớ nhung.', '我想喝咖啡，不想吃饭。', 'Tôi muốn uống cà phê, không muốn ăn cơm.', 1),
(5, 'Động từ 喜欢 với tân ngữ kép', '喜欢 + danh từ / động từ + tân ngữ', 'Sau 喜欢 có thể là danh từ hoặc cả một cụm động từ. Muốn nhấn mạnh mức độ thì thêm 很 hoặc 非常 phía trước.', '我很喜欢吃中国菜，也喜欢中国茶。', 'Tôi rất thích ăn món Trung Quốc, cũng thích trà Trung Quốc.', 2),
(5, 'Phủ định với 不', '不 + động từ / tính từ', 'Phó từ 不 phủ định thói quen, ý muốn hoặc trạng thái hiện tại và tương lai. Riêng với động từ 有 phải dùng 没有. Thanh điệu của 不 biến thành thanh 2 khi đứng trước âm tiết thanh 4.', '我不吃肉，也不喝酒。', 'Tôi không ăn thịt, cũng không uống rượu.', 3),
(6, 'Hỏi giá với 多少钱', 'Vật + 多少钱？', 'Đây là mẫu câu hỏi giá cố định. Đơn vị tiền khẩu ngữ là 块, 毛, 分, còn văn viết dùng 元, 角, 分.', '这件衣服多少钱？三十五块。', 'Chiếc áo này bao nhiêu tiền? Ba mươi lăm tệ.', 1),
(6, 'Lượng từ thường gặp 个, 本, 件', 'Số từ + lượng từ + danh từ', 'Giữa số từ và danh từ bắt buộc có lượng từ. 个 dùng chung cho người và vật, 本 dùng cho sách vở, 件 dùng cho quần áo và sự việc, 张 dùng cho vật phẳng.', '我买两本书和一件衣服。', 'Tôi mua hai quyển sách và một chiếc áo.', 2),
(6, 'Cấu trúc cảm thán 太…了', '太 + tính từ + 了', 'Cấu trúc 太…了 diễn tả mức độ vượt quá, mang sắc thái cảm thán, thường dùng khi khen hoặc chê. Dạng phủ định 不太 lại chỉ mức độ nhẹ đi.', '太贵了！这儿的东西不太便宜。', 'Đắt quá! Đồ ở đây không rẻ lắm.', 3),
(7, 'Động từ 在 chỉ vị trí', 'Vật + 在 + nơi chốn', 'Động từ 在 nói vật hoặc người ở đâu. Hỏi vị trí dùng 在哪儿. Phủ định là 不在.', '书在桌子上，老师不在办公室。', 'Sách ở trên bàn, cô giáo không có ở văn phòng.', 1),
(7, 'Từ chỉ phương vị đặt sau danh từ', 'Danh từ + 上/里/下/前/后', 'Từ chỉ phương vị trong tiếng Trung đứng SAU danh từ nơi chốn, ngược với tiếng Việt. 桌子上 nghĩa là trên bàn, 房间里 nghĩa là trong phòng.', '房间里有一台电脑，桌子下有一个包。', 'Trong phòng có một máy tính, dưới bàn có một cái túi.', 2),
(7, 'Đại từ chỉ định 这 và 那', '这/那 + lượng từ + danh từ', 'Đại từ 这 chỉ vật ở gần, 那 chỉ vật ở xa. Khi đi với danh từ đếm được phải chèn lượng từ ở giữa: 这本书, 那个人.', '这本书是我的，那个杯子是他的。', 'Quyển sách này là của tôi, cái cốc kia là của cậu ấy.', 3),
(8, 'Động từ năng nguyện 会', 'Chủ ngữ + 会 + động từ', 'Động từ 会 chỉ kỹ năng có được nhờ học tập, phủ định là 不会. Muốn nói mức độ ít thì thêm 一点儿 sau tân ngữ.', '我会说汉语，但是不会写汉字。', 'Tôi biết nói tiếng Trung nhưng không biết viết chữ Hán.', 1),
(8, 'Giới từ 在 chỉ nơi chốn của hành động', 'Chủ ngữ + 在 + nơi chốn + động từ', 'Khi 在 làm giới từ, cụm giới từ phải đứng TRƯỚC động từ chính. Không được nói 我学习在学校 theo trật tự tiếng Việt.', '我在大学学习汉语。', 'Tôi học tiếng Trung ở trường đại học.', 2),
(8, 'Liên từ 和 nối danh từ', 'Danh từ + 和 + danh từ', 'Liên từ 和 chỉ nối danh từ hoặc đại từ, không dùng để nối hai mệnh đề như chữ và trong tiếng Việt. Muốn nối hai câu thì dùng dấu phẩy hoặc phó từ 也.', '我和我的同学都喜欢汉语。', 'Tôi và bạn học của tôi đều thích tiếng Trung.', 3),
(9, 'Câu vị ngữ tính từ với 很', 'Chủ ngữ + 很 + tính từ', 'Câu vị ngữ tính từ không dùng động từ 是. Phó từ 很 giữ vai trò liên kết, thường không mang nghĩa rất khi không nhấn trọng âm.', '今天很热，昨天很冷。', 'Hôm nay rất nóng, hôm qua rất lạnh.', 1),
(9, 'Phủ định câu vị ngữ tính từ', 'Chủ ngữ + 不 + tính từ', 'Khi phủ định câu vị ngữ tính từ, bỏ 很 và thay bằng 不. Muốn giảm nhẹ thì dùng 不太.', '今天不冷，天气不太好。', 'Hôm nay không lạnh, thời tiết không được đẹp lắm.', 2),
(9, 'Hỏi tình trạng với 怎么样', 'Chủ đề + 怎么样？', 'Cụm 怎么样 hỏi về tình trạng, chất lượng hoặc ý kiến, tương đương thế nào trong tiếng Việt. Cũng dùng để đề nghị: 我们去看电影，怎么样？', '今天天气怎么样？这个菜怎么样？', 'Thời tiết hôm nay thế nào? Món này thế nào?', 3),
(10, 'Câu liên động chỉ phương tiện', 'Chủ ngữ + 坐/骑 + phương tiện + 去 + nơi chốn', 'Hai động từ nối nhau theo đúng trình tự xảy ra: trước hết lên phương tiện, sau đó tới nơi. Xe đạp và xe máy dùng 骑, các phương tiện có chỗ ngồi dùng 坐.', '我坐公共汽车去学校，他骑自行车去。', 'Tôi đi xe buýt tới trường, cậu ấy đi xe đạp.', 1),
(10, 'Động từ 去 và 来', '去/来 + nơi chốn', 'Động từ 去 chỉ hướng đi xa khỏi người nói, 来 chỉ hướng tới gần người nói. Sau hai động từ này, danh từ nơi chốn đứng trực tiếp, không cần giới từ.', '你去哪儿？我来北京学习汉语。', 'Bạn đi đâu? Tôi đến Bắc Kinh học tiếng Trung.', 2),
(10, 'Hỏi cách thức với 怎么', '怎么 + động từ', 'Từ để hỏi 怎么 hỏi về phương thức tiến hành hành động, đứng ngay trước động từ. Cần phân biệt với 怎么样 hỏi tình trạng.', '这个字怎么读？你怎么去机场？', 'Chữ này đọc thế nào? Bạn tới sân bay bằng cách nào?', 3),
(11, 'Trợ từ 了 chỉ sự thay đổi trạng thái', 'Câu + 了', 'Chữ 了 đứng cuối câu báo hiệu tình hình đã thay đổi so với trước đó. 我生病了 nghĩa là trước khỏe, giờ đã ốm.', '我生病了，不能去上课了。', 'Tôi bị ốm rồi, không đi học được nữa.', 1),
(11, 'Phân biệt phủ định 不 và 没', '不 + động từ (hiện tại, tương lai) / 没 + động từ (quá khứ)', 'Phó từ 不 phủ định ý muốn, thói quen, tình trạng hiện tại và tương lai. Phó từ 没 phủ định việc đã không xảy ra hoặc chưa xảy ra trong quá khứ.', '我昨天没去医院，今天也不想去。', 'Hôm qua tôi đã không đi bệnh viện, hôm nay cũng không muốn đi.', 2),
(11, 'Câu cầu khiến lịch sự với 请', '请 + động từ + tân ngữ', 'Chữ 请 đặt đầu câu làm lời đề nghị trở nên lịch sự, tương đương xin mời hoặc làm ơn trong tiếng Việt.', '请坐，请喝茶，请再说一遍。', 'Mời ngồi, mời uống trà, xin nói lại một lần nữa.', 3),
(12, 'Trật tự thành phần câu tiếng Trung', 'Chủ ngữ + thời gian + nơi chốn + phương thức + động từ + tân ngữ', 'Đây là bộ khung trật tự cố định của câu tiếng Trung. Nhớ đúng thứ tự này giúp tránh phần lớn lỗi sai khi dịch từ tiếng Việt sang.', '我明天在家跟朋友一起看电视。', 'Ngày mai tôi xem tivi cùng bạn ở nhà.', 1),
(12, 'Câu hỏi chính phản', 'Động từ + 不 + động từ', 'Ghép dạng khẳng định và phủ định của cùng một động từ hoặc tính từ để tạo câu hỏi, sắc thái tương đương câu hỏi với 吗 nhưng không được dùng chung với 吗.', '你去不去？这个菜好吃不好吃？', 'Bạn có đi không? Món này có ngon không?', 2),
(12, 'Câu hỏi lược với 呢', 'Danh từ / đại từ + 呢？', 'Trợ từ 呢 tạo câu hỏi rút gọn dựa trên nội dung vừa nói, tránh lặp lại cả câu. Ngoài ra 呢 còn hỏi vị trí: 我的书呢？', '我很好，你呢？我的手机呢？', 'Tôi khỏe, còn bạn? Điện thoại của tôi đâu rồi?', 3);

-- ---------------------------------------------------------------------
-- 7. LESSON_GRAMMAR - diem ngu phap khoa 2 (bai 13..24), 3 diem / bai
-- ---------------------------------------------------------------------
INSERT INTO lesson_grammar (lesson_id, title, structure, explanation, example_zh, example_vi, sort_order) VALUES
(13, 'Cấu trúc 从…到… chỉ điểm đầu và điểm cuối', '从 + A + 到 + B', 'Cặp giới từ 从…到… dùng cho cả khoảng không gian lẫn khoảng thời gian. Cụm này đứng trước động từ chính của câu.', '从我家到公司要三十分钟。', 'Từ nhà tôi tới công ty mất ba mươi phút.', 1),
(13, 'Giới từ 往 chỉ hướng di chuyển', '往 + phương hướng + động từ', 'Giới từ 往 nêu hướng của hành động và luôn đứng trước động từ. Các từ hướng thường gặp: 前, 后, 左, 右, 东, 西.', '一直往前走，到路口往右拐。', 'Cứ đi thẳng, tới ngã tư thì rẽ phải.', 2),
(13, 'Giới từ 离 chỉ khoảng cách', 'A + 离 + B + 远/近', 'Giới từ 离 nói khoảng cách giữa hai điểm, thường đi với 远, 近 hoặc một con số cụ thể. Đừng nhầm 离 với 从.', '我家离学校很近，只有一公里。', 'Nhà tôi rất gần trường, chỉ một cây số.', 3),
(14, 'Động từ 要 khi gọi món', 'Chủ ngữ + 要 + số lượng + lượng từ + món ăn', 'Động từ 要 mang nghĩa muốn lấy, dùng phổ biến khi gọi món và mua hàng. Sắc thái dứt khoát hơn 想. Phủ định lịch sự là 不用了.', '我要一碗牛肉面和一杯茶。', 'Cho tôi một bát mì bò và một cốc trà.', 1),
(14, 'Câu hỏi lựa chọn với 还是', 'A + 还是 + B？', 'Liên từ 还是 dùng trong câu hỏi để đưa ra hai lựa chọn. Trong câu trần thuật phải dùng 或者 chứ không dùng 还是.', '你喝茶还是喝咖啡？', 'Bạn uống trà hay uống cà phê?', 2),
(14, 'Phân biệt 有点儿 và 一点儿', '有点儿 + tính từ / tính từ + 一点儿', 'Cụm 有点儿 đứng trước tính từ và mang sắc thái không hài lòng. Cụm 一点儿 đứng sau tính từ, chỉ mức độ chênh lệch nhỏ và thường dùng khi đề nghị.', '这个菜有点儿咸，请淡一点儿。', 'Món này hơi mặn, làm ơn nhạt hơn một chút.', 3),
(15, 'Phó từ tần suất 常常 và 有时候', 'Chủ ngữ + 常常/有时候 + động từ', 'Phó từ chỉ tần suất đứng trước động từ. 常常 nhấn mạnh việc lặp lại thường xuyên, 有时候 chỉ đôi lúc, 从来不 nghĩa là chưa bao giờ.', '我常常去游泳，有时候去爬山。', 'Tôi thường đi bơi, thỉnh thoảng đi leo núi.', 1),
(15, 'Động từ 觉得 nêu cảm nhận', 'Chủ ngữ + 觉得 + mệnh đề', 'Động từ 觉得 dẫn ra nhận xét chủ quan, theo sau là cả một mệnh đề chứ không phải một danh từ đơn lẻ.', '我觉得学汉语很有意思。', 'Tôi thấy học tiếng Trung rất thú vị.', 2),
(15, 'Giới từ 跟 chỉ đối tượng cùng làm', 'Chủ ngữ + 跟 + người + động từ', 'Giới từ 跟 nêu người cùng thực hiện hành động, đứng trước động từ, thường đi kèm phó từ 一起.', '周末我跟朋友一起去看电影。', 'Cuối tuần tôi đi xem phim cùng bạn.', 3),
(16, 'Giới từ 在 chỉ nơi làm việc', 'Chủ ngữ + 在 + nơi chốn + động từ', 'Cụm giới từ chỉ nơi chốn bắt buộc đứng trước động từ. Đây là lỗi sai kinh điển vì tiếng Việt đặt nơi chốn ở cuối câu.', '我在一家中国公司工作。', 'Tôi làm việc ở một công ty Trung Quốc.', 1),
(16, 'Cặp liên từ 因为…所以…', '因为 + nguyên nhân, 所以 + kết quả', 'Tiếng Trung thường dùng đủ cả hai vế của cặp liên từ, khác tiếng Việt hay lược bớt một vế. Có thể đảo vế kết quả lên trước.', '因为今天有会议，所以我不能去。', 'Vì hôm nay có cuộc họp nên tôi không đi được.', 2),
(16, 'Phó từ 已经 kết hợp với 了', '已经 + động từ + 了', 'Phó từ 已经 chỉ việc đã hoàn tất và hầu như luôn đi cùng trợ từ 了 ở cuối câu. Phủ định dùng 还没有…呢.', '我已经工作三年了，还没有换工作呢。', 'Tôi đã đi làm ba năm rồi, vẫn chưa đổi việc.', 3),
(17, 'Câu so sánh với 比', 'A + 比 + B + tính từ', 'Công thức so sánh hơn cơ bản nhất. Sau tính từ không được thêm 很 hay 太, nhưng có thể thêm 一点儿, 多了 hoặc con số cụ thể để nêu mức chênh lệch.', '这件衣服比那件贵一点儿。', 'Chiếc áo này đắt hơn chiếc kia một chút.', 1),
(17, 'Động từ năng nguyện 可以 xin phép', '可以 + động từ + 吗？', 'Động từ 可以 dùng để xin phép hoặc hỏi khả năng được phép. Trả lời đồng ý là 可以, từ chối thường dùng 不行 chứ ít khi nói 不可以 trực diện.', '我可以试试这件衣服吗？', 'Tôi mặc thử chiếc áo này được không?', 2),
(17, 'Kết cấu chữ 的 thay thế danh từ', 'Tính từ / màu sắc + 的', 'Khi ngữ cảnh đã rõ, có thể lược danh từ phía sau 的 và dùng cụm 的 làm chủ ngữ hoặc tân ngữ, tương đương cái màu đỏ, cái rẻ trong tiếng Việt.', '我要红色的，不要白色的。', 'Tôi lấy cái màu đỏ, không lấy cái màu trắng.', 3),
(18, 'Động từ năng nguyện 要 chỉ sự cần thiết', 'Chủ ngữ + 要 + động từ', 'Ở đây 要 mang nghĩa cần phải, nên. Điều đặc biệt là phủ định của nó không phải 不要 mà là 不用, vì 不要 nghĩa là đừng.', '你要多休息，不用吃药。', 'Bạn cần nghỉ ngơi nhiều, không cần uống thuốc.', 1),
(18, 'Câu cầu khiến phủ định với 别', '别 + động từ + tân ngữ', 'Phó từ 别 đặt đầu vị ngữ để khuyên đừng làm gì. Thêm 请 phía trước cho lịch sự, thêm 了 cuối câu để yêu cầu dừng việc đang làm.', '别吃太冷的东西，别熬夜了。', 'Đừng ăn đồ quá lạnh, đừng thức khuya nữa.', 2),
(18, 'Cách nói tần suất dùng thuốc với 次', 'Thời gian + động từ + số + 次', 'Lượng từ động tác 次 đếm số lần thực hiện hành động, đứng sau động từ. Đây là bổ ngữ số lượng động tác rất hay gặp khi nói về liều thuốc.', '这个药一天吃三次，一次两片。', 'Thuốc này ngày uống ba lần, mỗi lần hai viên.', 3),
(19, 'Động từ 打算 nêu dự định', 'Chủ ngữ + 打算 + động từ', 'Động từ 打算 diễn tả kế hoạch đã cân nhắc, mức độ chắc chắn cao hơn 想. Phủ định là 不打算.', '我打算下个月去北京旅游。', 'Tôi định tháng sau đi du lịch Bắc Kinh.', 1),
(19, 'Giới từ 帮 nhờ vả', '帮 + người + động từ', 'Giới từ 帮 nêu người được giúp, đứng trước động từ. Thêm 请 ở đầu và 一下 ở cuối câu khiến lời nhờ vả nhẹ nhàng hơn nhiều.', '请帮我叫一辆出租车。', 'Làm ơn gọi giúp tôi một chiếc taxi.', 2),
(19, 'Hình thức lặp động từ', 'Động từ + động từ hoặc động từ + 一下', 'Lặp lại động từ hoặc thêm 一下 làm giảm mức độ trang trọng, mang nghĩa làm thử một chút, khiến câu nói thân thiện và lịch sự hơn.', '你等一下，我看看这个房间。', 'Bạn đợi một chút, để tôi xem qua căn phòng này.', 3),
(20, 'Cấu trúc 正在…呢 chỉ hành động đang diễn ra', '正在 + động từ + 呢', 'Cấu trúc này nói hành động đang tiếp diễn tại thời điểm nói. Có thể lược bớt thành 在…呢 hoặc chỉ dùng 呢 ở cuối câu.', '他正在开会呢，等一下再打吧。', 'Anh ấy đang họp, lát nữa gọi lại nhé.', 1),
(20, 'Giới từ 给 chỉ đối tượng tiếp nhận', '给 + người + động từ', 'Giới từ 给 đứng TRƯỚC động từ, khác hẳn tiếng Việt đặt cho ở cuối câu. Nói 给妈妈打电话, không nói 打电话给妈妈.', '我晚上给你打电话。', 'Tối tôi gọi điện cho bạn.', 2),
(20, 'Cách đề nghị với 好吗 và 吧', 'Câu đề nghị + 好吗？/ 吧', 'Thêm 好吗 cuối câu để hỏi ý kiến người nghe một cách lịch sự, thêm 吧 để đưa ra đề nghị hoặc thúc giục nhẹ nhàng.', '我们一起去吃饭，好吗？走吧！', 'Chúng ta cùng đi ăn nhé? Đi thôi!', 3),
(21, 'Động từ năng nguyện 会 chỉ khả năng xảy ra', '会 + động từ + 的', 'Ngoài nghĩa biết làm, 会 còn dùng để dự đoán khả năng xảy ra trong tương lai, thường thêm 的 cuối câu để tăng mức khẳng định.', '天气预报说明天会下雨。', 'Dự báo thời tiết nói ngày mai trời sẽ mưa.', 1),
(21, 'Cấu trúc 又…又… nêu hai đặc điểm', '又 + tính từ A + 又 + tính từ B', 'Cấu trúc này nối hai tính chất cùng tồn tại và cùng sắc thái, cả hai cùng khen hoặc cùng chê chứ không trộn lẫn.', '今天又闷又热，很不舒服。', 'Hôm nay vừa oi vừa nóng, rất khó chịu.', 2),
(21, 'Câu điều kiện 如果…就…', '如果 + điều kiện, 就 + kết quả', 'Vế điều kiện dùng 如果 hoặc 要是, vế kết quả gần như luôn có phó từ hô ứng 就. Có thể thêm 的话 sau vế điều kiện.', '如果明天不下雨，我们就去公园。', 'Nếu ngày mai không mưa thì chúng ta đi công viên.', 3),
(22, 'Bổ ngữ trạng thái với 得', 'Động từ + 得 + tính từ', 'Bổ ngữ trạng thái nhận xét mức độ của hành động. Nếu động từ có tân ngữ thì phải lặp lại động từ, hoặc đưa tân ngữ lên trước chủ ngữ.', '他汉语说得很流利。', 'Cậu ấy nói tiếng Trung rất trôi chảy.', 1),
(22, 'Cấu trúc 快要…了 chỉ việc sắp xảy ra', '快要 + động từ / tính từ + 了', 'Cấu trúc 快要…了 và 就要…了 đều nói việc sắp xảy ra, nhưng chỉ 就要…了 mới dùng được cùng mốc thời gian cụ thể phía trước.', '快要考试了，我很紧张。', 'Sắp thi rồi, tôi rất căng thẳng.', 2),
(22, 'Cặp liên từ 虽然…但是…', '虽然 + mệnh đề, 但是 + mệnh đề', 'Cặp liên từ nhượng bộ này luôn dùng đủ hai vế trong tiếng Trung, khác tiếng Việt thường lược bỏ một vế.', '虽然汉语很难，但是很有意思。', 'Tuy tiếng Trung rất khó nhưng rất thú vị.', 3),
(23, 'Cụm 长得 miêu tả ngoại hình', 'Chủ thể + 长得 + tính từ / 像 + người', 'Cụm 长得 chuyên dùng cho ngoại hình bẩm sinh, thường kết hợp với 像 để nói giống ai.', '他长得很像他爸爸。', 'Cậu ấy trông rất giống bố mình.', 1),
(23, 'So sánh nhất với 最', '最 + tính từ + 的 + danh từ', 'Phó từ 最 tạo so sánh cấp cao nhất trong một phạm vi, phạm vi đó thường được nêu rõ bằng cụm chỉ nhóm đứng trước.', '她是我们班最认真的学生。', 'Cô ấy là học sinh chăm chỉ nhất lớp chúng tôi.', 2),
(23, 'Giới từ 对 nêu thái độ hướng tới ai', 'A + 对 + B + tính từ / động từ', 'Giới từ 对 nêu đối tượng mà thái độ hoặc ảnh hưởng hướng tới, cụm này đứng trước vị ngữ.', '我的同事对我很热情。', 'Đồng nghiệp rất nhiệt tình với tôi.', 3),
(24, 'Trợ từ 了 chỉ hành động hoàn thành', 'Động từ + 了 + tân ngữ', 'Trợ từ động thái 了 đứng ngay sau động từ để nói hành động đã hoàn thành. Phủ định dùng 没 và phải bỏ 了.', '我吃了饭就去上班了。', 'Tôi ăn cơm xong là đi làm luôn.', 1),
(24, 'Trợ từ 过 chỉ kinh nghiệm', 'Động từ + 过 + tân ngữ', 'Trợ từ 过 nói từng trải qua việc gì trong quá khứ, nhấn mạnh kinh nghiệm chứ không nhấn mạnh sự hoàn tất. Phủ định là 没…过.', '我去过中国，没吃过北京烤鸭。', 'Tôi từng đi Trung Quốc, chưa từng ăn vịt quay Bắc Kinh.', 2),
(24, 'Phân biệt 了, 过 và 正在', '了 hoàn thành / 过 kinh nghiệm / 正在 đang diễn ra', 'Ba trợ từ và phó từ này đánh dấu thì và thể của hành động, là nội dung trọng tâm của kỳ thi HSK 2. Nhớ rằng tiếng Trung không chia động từ, mọi thông tin thời gian nằm ở các từ đánh dấu này.', '他昨天来了，我以前见过他，现在他正在休息。', 'Hôm qua anh ấy đã đến, trước đây tôi từng gặp anh ấy, bây giờ anh ấy đang nghỉ.', 3);

-- ---------------------------------------------------------------------
-- 8. LESSON_WORDS - gan tu vung cho tung bai hoc
--    Bai 1..12  (khoa HSK 1) dung words id 1..144   (nam trong 1..150)
--    Bai 13..24 (khoa HSK 2) dung words id 151..294 (nam trong 151..300)
--    Moi bai 12 tu, sort_order 0..11, khong ghi id (bang khoa kep).
-- ---------------------------------------------------------------------
INSERT INTO lesson_words (lesson_id, word_id, sort_order) VALUES
(1, 1, 0),
(1, 2, 1),
(1, 3, 2),
(1, 4, 3),
(1, 5, 4),
(1, 6, 5),
(1, 7, 6),
(1, 8, 7),
(1, 9, 8),
(1, 10, 9),
(1, 11, 10),
(1, 12, 11),
(2, 13, 0),
(2, 14, 1),
(2, 15, 2),
(2, 16, 3),
(2, 17, 4),
(2, 18, 5),
(2, 19, 6),
(2, 20, 7),
(2, 21, 8),
(2, 22, 9),
(2, 23, 10),
(2, 24, 11),
(3, 25, 0),
(3, 26, 1),
(3, 27, 2),
(3, 28, 3),
(3, 29, 4),
(3, 30, 5),
(3, 31, 6),
(3, 32, 7),
(3, 33, 8),
(3, 34, 9),
(3, 35, 10),
(3, 36, 11),
(4, 37, 0),
(4, 38, 1),
(4, 39, 2),
(4, 40, 3),
(4, 41, 4),
(4, 42, 5),
(4, 43, 6),
(4, 44, 7),
(4, 45, 8),
(4, 46, 9),
(4, 47, 10),
(4, 48, 11),
(5, 49, 0),
(5, 50, 1),
(5, 51, 2),
(5, 52, 3),
(5, 53, 4),
(5, 54, 5),
(5, 55, 6),
(5, 56, 7),
(5, 57, 8),
(5, 58, 9),
(5, 59, 10),
(5, 60, 11),
(6, 61, 0),
(6, 62, 1),
(6, 63, 2),
(6, 64, 3),
(6, 65, 4),
(6, 66, 5),
(6, 67, 6),
(6, 68, 7),
(6, 69, 8),
(6, 70, 9),
(6, 71, 10),
(6, 72, 11),
(7, 73, 0),
(7, 74, 1),
(7, 75, 2),
(7, 76, 3),
(7, 77, 4),
(7, 78, 5),
(7, 79, 6),
(7, 80, 7),
(7, 81, 8),
(7, 82, 9),
(7, 83, 10),
(7, 84, 11),
(8, 85, 0),
(8, 86, 1),
(8, 87, 2),
(8, 88, 3),
(8, 89, 4),
(8, 90, 5),
(8, 91, 6),
(8, 92, 7),
(8, 93, 8),
(8, 94, 9),
(8, 95, 10),
(8, 96, 11),
(9, 97, 0),
(9, 98, 1),
(9, 99, 2),
(9, 100, 3),
(9, 101, 4),
(9, 102, 5),
(9, 103, 6),
(9, 104, 7),
(9, 105, 8),
(9, 106, 9),
(9, 107, 10),
(9, 108, 11),
(10, 109, 0),
(10, 110, 1),
(10, 111, 2),
(10, 112, 3),
(10, 113, 4),
(10, 114, 5),
(10, 115, 6),
(10, 116, 7),
(10, 117, 8),
(10, 118, 9),
(10, 119, 10),
(10, 120, 11),
(11, 121, 0),
(11, 122, 1),
(11, 123, 2),
(11, 124, 3),
(11, 125, 4),
(11, 126, 5),
(11, 127, 6),
(11, 128, 7),
(11, 129, 8),
(11, 130, 9),
(11, 131, 10),
(11, 132, 11),
(12, 133, 0),
(12, 134, 1),
(12, 135, 2),
(12, 136, 3),
(12, 137, 4),
(12, 138, 5),
(12, 139, 6),
(12, 140, 7),
(12, 141, 8),
(12, 142, 9),
(12, 143, 10),
(12, 144, 11),
(13, 151, 0),
(13, 152, 1),
(13, 153, 2),
(13, 154, 3),
(13, 155, 4),
(13, 156, 5),
(13, 157, 6),
(13, 158, 7),
(13, 159, 8),
(13, 160, 9),
(13, 161, 10),
(13, 162, 11),
(14, 163, 0),
(14, 164, 1),
(14, 165, 2),
(14, 166, 3),
(14, 167, 4),
(14, 168, 5),
(14, 169, 6),
(14, 170, 7),
(14, 171, 8),
(14, 172, 9),
(14, 173, 10),
(14, 174, 11),
(15, 175, 0),
(15, 176, 1),
(15, 177, 2),
(15, 178, 3),
(15, 179, 4),
(15, 180, 5),
(15, 181, 6),
(15, 182, 7),
(15, 183, 8),
(15, 184, 9),
(15, 185, 10),
(15, 186, 11),
(16, 187, 0),
(16, 188, 1),
(16, 189, 2),
(16, 190, 3),
(16, 191, 4),
(16, 192, 5),
(16, 193, 6),
(16, 194, 7),
(16, 195, 8),
(16, 196, 9),
(16, 197, 10),
(16, 198, 11),
(17, 199, 0),
(17, 200, 1),
(17, 201, 2),
(17, 202, 3),
(17, 203, 4),
(17, 204, 5),
(17, 205, 6),
(17, 206, 7),
(17, 207, 8),
(17, 208, 9),
(17, 209, 10),
(17, 210, 11),
(18, 211, 0),
(18, 212, 1),
(18, 213, 2),
(18, 214, 3),
(18, 215, 4),
(18, 216, 5),
(18, 217, 6),
(18, 218, 7),
(18, 219, 8),
(18, 220, 9),
(18, 221, 10),
(18, 222, 11),
(19, 223, 0),
(19, 224, 1),
(19, 225, 2),
(19, 226, 3),
(19, 227, 4),
(19, 228, 5),
(19, 229, 6),
(19, 230, 7),
(19, 231, 8),
(19, 232, 9),
(19, 233, 10),
(19, 234, 11),
(20, 235, 0),
(20, 236, 1),
(20, 237, 2),
(20, 238, 3),
(20, 239, 4),
(20, 240, 5),
(20, 241, 6),
(20, 242, 7),
(20, 243, 8),
(20, 244, 9),
(20, 245, 10),
(20, 246, 11),
(21, 247, 0),
(21, 248, 1),
(21, 249, 2),
(21, 250, 3),
(21, 251, 4),
(21, 252, 5),
(21, 253, 6),
(21, 254, 7),
(21, 255, 8),
(21, 256, 9),
(21, 257, 10),
(21, 258, 11),
(22, 259, 0),
(22, 260, 1),
(22, 261, 2),
(22, 262, 3),
(22, 263, 4),
(22, 264, 5),
(22, 265, 6),
(22, 266, 7),
(22, 267, 8),
(22, 268, 9),
(22, 269, 10),
(22, 270, 11),
(23, 271, 0),
(23, 272, 1),
(23, 273, 2),
(23, 274, 3),
(23, 275, 4),
(23, 276, 5),
(23, 277, 6),
(23, 278, 7),
(23, 279, 8),
(23, 280, 9),
(23, 281, 10),
(23, 282, 11),
(24, 283, 0),
(24, 284, 1),
(24, 285, 2),
(24, 286, 3),
(24, 287, 4),
(24, 288, 5),
(24, 289, 6),
(24, 290, 7),
(24, 291, 8),
(24, 292, 9),
(24, 293, 10),
(24, 294, 11);
